### PR TITLE
vendor: github.com/docker/docker 59996a493cfc (v27.0.0-dev)

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/docker/docker/compare/181e70cc078e...59996a493cfc36871ddd8f6ede525def98b69e2f

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by laurazard — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
I'll bring this one in; we'll do more updates as we go.

**Comment by thaJeztah** [comment]
LOL; you're not in "runtime owners"? So your LGTM doesn't apply? fun!

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
> LOL; you're not in "runtime owners"? So your LGTM doesn't apply? fun!

Fixed as well

**Pull request merged**
