### PR TITLE
[18.09] Fix progress reporting for containerd pulls

### PR DESCRIPTION
**Pull request by dhiltgen**
During refactoring of the implementation PR progress reporting
was broken.  This gets the progress reporting back in action.

Signed-off-by: Daniel Hiltgen <daniel.hiltgen@docker.com>

### CODE REVIEW

**Comment by dhiltgen** [comment]
This will need to be cherry-picked to master as well

**Comment by crosbymichael** [comment]
LGTM

**Comment by andrewhsu** [comment]
@dhiltgen needs port to master branch?

**Comment by selansen** [comment]
LGTM

**Pull request merged**
