### PR TITLE
[carry] Add support for `template_driver` in composefiles

### PR DESCRIPTION
**Pull request by thaJeztah**
Carry of https://github.com/docker/cli/pull/1100 - rebased, and moved the option to schema 3.8
closes https://github.com/docker/cli/pull/1100

This maps the `--template-driver` flag on secret and config creation.

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @silvin-lubecki @vdemeester PTAL

**Comment by thaJeztah** [comment]
ah, saw that one coming 😅 - working on another PR, but I'll update after 👍

**Comment by thaJeztah** [comment]
rebased; regenerated cli/compose/schema/bindata.go

**Comment by masaeedu** [comment]
Is the documentation at https://docs.docker.com/compose/compose-file generated from the source code here or is that a separate repo altogether?

**Comment by thaJeztah** [comment]
@masaeedu documentation there is not generated automatically, but from a Markdown file in https://github.com/docker/docker.github.io/blob/master/compose/compose-file/index.md

**Comment by masaeedu** [comment]
@thaJeztah Would that repo be the right place to open an issue to add documentation concerning `template_driver` and what variables are available? If I `Ctrl+F` `template` on https://docs.docker.com/compose/compose-file/ I get nothing.

**Comment by thaJeztah** [comment]
@masaeedu yes, that would be the right place. I think the reason it wasn't documented yet, was that docker-compose (standalone) did not yet have support for the 3.8 schema until https://github.com/docker/compose/pull/7217 (which is in docker compose v1.25.5 and up: https://github.com/docker/compose/releases/tag/1.25.5.

I see https://github.com/docker/docker.github.io/pull/10273 added some of the changes, but didn't include all of them. Let me have a look at updating the docs

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/10980 to add some basic information (probably could use some enhancement after that, but at least the fields are mentioned now)

**Pull request merged**
