### PR TITLE
Add DefaultAddressPool to docker info

### PR DESCRIPTION
**Pull request by wangyumu**
**- What I did**
Related to PR: moby/moby/pull/40714

**- How I did it**
Print the `Default Address Pools` if it exists in `GET "/info"`

**- How to verify it**
The output of docker info:
```
# docker info
...
 Live Restore Enabled: false
 Default Address Pools:
  Base: 10.123.0.0/16, Size: 24
  Base: 10.12.0.0/16, Size: 24
```

**- Description for the changelog**
Add Default Address Pools to docker info output

**- A picture of a cute animal (not mandatory but encouraged)**
🐦

### CODE REVIEW

**Comment by thaJeztah** [comment]
changed title to "WIP", because this needs the upstream changes in moby to be merged first 👍

**Comment by thaJeztah** [comment]
depends on https://github.com/docker/cli/pull/2395, which updates the moby/moby dependency to have the API changes

**Comment by thaJeztah** [comment]
https://github.com/docker/cli/pull/2641 was merged; @wangyumu could you rebase this PR? Perhaps you could also update `TestPrettyPrintInfo` to test the output? https://github.com/docker/cli/blob/7cd6e893a1dd13808464cd683a9e57d73f6e83b7/cli/command/system/info_test.go#L224

**Comment by wangyumu** [comment]
@thaJeztah done, thanks.

**Comment by thaJeztah** [comment]
@silvin-lubecki @tiborvass PTAL

**Pull request merged**
