### PR TITLE
Import man docs completion

### PR DESCRIPTION
**Pull request by tiborvass**
This partially replaces https://github.com/docker/cli/pull/68.

ca8303e325756977fc96d61910d7b979341b4a41 is the merge commit that imports the changes
d2cb97e76d581f4a9c2fa9df9649a7d59d9474e3 and 875daf0 and d2976d5 are additional commits.

```
$ git checkout f888a25ff5     # engine commit used in docker-ce in 17.06 branch
$ git filter-branch -f -d /tmp/fb  --index-filter "git rm --cached -qr --ignore-unmatch -- . && git reset -q \$GIT_COMMIT -- $(echo experimental man docs/{README.md,deprecated.md,extend} docs/sources/experimental docs/{sources/,}reference/{glossary.md,builder.md,builder.rst,index.md,index.rst,run.md,run.rst,commandline} contrib/completion docs/yaml)" --prune-empty
$ git rebase -Xours --root HEAD
$ git rm man/docker-volume.1.md && git rebase --continue
$ git rm docs/deprecated.md && git rebase --continue
$ git branch -f tmp
$ git checkout 3dfb8343b139d6342acfd9975d7f1068b5b1c3d3   # cli commit used in docker-ce in 17.06 branch
$ git merge --allow-unrelated-histories tmp
$ git revert -e $(git log --format=%H -1 --follow -- docs/yaml)
$ # ... add the additional commits
```

Please note that this imports only up till what is in 17.06. The rest will be imported in another PR. This is so that it is easier to include this PR in the release branch of the docker-ce repo.

A follow up PR is also needed to change Makefiles and add scripts to generate both man pages and yaml docs. The reason it will be separate is because cli master and cli 17.06 have diverged for those.

### CODE REVIEW

**Comment by andrewhsu** [comment]
Datapoint for expected number of files in man directories from docker-ce 17.05.0:
```
$ rpm -ql docker-ce-17.05.0.ce | grep /usr/share/man/man1 | wc -l
151
$ rpm -ql docker-ce-17.05.0.ce | grep /usr/share/man/man5 | wc -l
2
$ rpm -ql docker-ce-17.05.0.ce | grep /usr/share/man/man8 | wc -l
1
```

**Comment by dnephin** [comment]
@tiborvass Ci was failing because of imports. I forced pushed a commit to this branch with the following changes:
* dropped the commit which excluded these scripts from linting
* add missing dependencies to vendor (it's only 3 files, we may as well add them)
* fixed the imports in both files (your commit only fixed one, and I think it was dropped somehow, because I didn't see the commit you referenced in the description in this PR)

**Comment by dnephin** [comment]
If you haven't started on the Makefile/scripts for running these generations, let me know. I can open a PR to add them.

**Comment by dnephin** [comment]
@andrewhsu I was looking at that same diff. The problem is you're diffing against master, not 3dfb8343b139d6342acfd9975d7f1068b5b1c3d3. This was branched from 3dfb8343b139d6342acfd9975d7f1068b5b1c3d3.

**Comment by andrewhsu** [comment]
@dnephin cool, thanks for pointing that out. diff now looks good on that front:
```
$ git diff --stat 3dfb834 tv/import-man-docs-completion | grep '^ cli' # no changes to golang code in cli which is good
```

**Comment by tiborvass** [comment]
@dnephin About vendor.conf change, I was thinking of not adding it in the main dockerfile, since it's not needed for the cli, just for the man pages. But I don't mind if it's fine for you.

LGTM

**Comment by vieux** [comment]
LGTM let's merge this soon before it diverges too much.

**Pull request merged**
