### PR TITLE
Remove k8s.io/kubernetes dependency

### PR DESCRIPTION
**Pull request by rumpl**
**- What I did**

Removed the `k8s.io/kubernetes` dependency, we are only using the `IsPodReady` function that can be rewritten.
This [shouldn't be imported as a library anyway](https://github.com/kubernetes/kubernetes/issues/90358#issuecomment-617859364)

**- How I did it**

Replaced the call to `podutils.IsPodReady` with a custom function.

**- How to verify it**

I am not really sure, would need help if there are no tests that cover this code.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**
image

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM ❤️

**Comment by thaJeztah** [comment]
@silvin-lubecki PTAL

**Review by chris-crone — APPROVED** [review]
LGTM!

**Review by silvin-lubecki — APPROVED** [review]
LGTM ❤️ 🤯

**Pull request merged**
