### PR TITLE
[18.09] bump docker/engine

### PR DESCRIPTION
**Pull request by kolyshkin**
1. Bump `docker/engine` to include https://github.com/docker/engine/pull/188
2. Bump `prometheus/*` and `swarmkit` to match docker/engine's vendor.conf

### CODE REVIEW

**Comment by kolyshkin** [comment]
@andrewhsu @thaJeztah PTAL (related to https://github.com/docker/engine/pull/188)

**Comment by andrewhsu** [comment]
Hmm...[something](https://circleci.com/gh/docker/cli/27296?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) about unmount:
```
# github.com/docker/cli/vendor/github.com/docker/docker/pkg/mount
vendor/github.com/docker/docker/pkg/mount/mount.go:126:9: undefined: unmount
vendor/github.com/docker/docker/pkg/mount/mount.go:144:9: undefined: unmount
```

**Comment by kolyshkin** [comment]
> Hmm...something about unmount:

Ughm, I always forget to do `git add` after running `vndr`. Should be fixed now.

**Comment by andrewhsu** [comment]
Closer. Just PR check for `ci/circleci: cross` [failing](https://circleci.com/gh/docker/cli/27311?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link):
```
# github.com/docker/cli/vendor/github.com/docker/docker/pkg/mount
vendor/github.com/docker/docker/pkg/mount/unmount_unix.go:7:6: unmount redeclared in this block
	previous declaration at vendor/github.com/docker/docker/pkg/mount/mounter_unsupported.go:9:39
```

**Comment by kolyshkin** [comment]
Building build/docker-darwin-amd64
# github.com/docker/cli/vendor/github.com/docker/docker/pkg/mount
vendor/github.com/docker/docker/pkg/mount/unmount_unix.go:7:6: unmount redeclared in this block
	previous declaration at vendor/github.com/docker/docker/pkg/mount/mounter_unsupported.go:9:39

Hmm, I remember we have fixed this in upstream moby/moby. Yes, this is  moby/moby#38372 which apparently needs to be backported to 18.09. Stay tuned

**Comment by kolyshkin** [comment]
Marked as WIP as this needs https://github.com/docker/engine/pull/379 to be merged and then a re-vendor

**Comment by kolyshkin** [comment]
@thaJeztah PTAL. Also, does this actually fix a bug in the client?

**Comment by kolyshkin** [comment]
I have checked all the docker/engine's vendor.conf bumps that appeared in this PR and compared the new versions to those in cli's vendor.conf. It looks like all the components (changed in docker/engine vendor.conf) are of the same version in cli vendor.conf, except:

These ones are newer in cli:

| component | version in engine's vendor.conf | version in cli's vendor.conf |
| --------------- | ----------------------- | ----------------- |
| docker/swarmkit |  https://github.com/docker/swarmkit/commit/142a73731c850daf24d32001aa2358b6ffe36eab (Jul 29) | https://github.com/docker/swarmkit/commit/cfa742c8abe6f8e922f6e4e920153c408e7d9c3b (Aug 19) |

These ones are older in CLI, and I'm going to bump those:

github.com/prometheus/*

**Comment by kolyshkin** [comment]
Updated with github.com/prometheus/* bumps to match those in docker/engine

**Comment by kolyshkin** [comment]
I wrote a half-assed script to figure out the differences in vendoring between the two; here is the script:

```bash
#!/bin/bash

set -u

get_sha() {
	if echo -n $1 | grep -qE '^[0-9a-f]{40}$'; then
		echo $1
		return
	fi
	# figure it out the hard way
#	go get -u $2 > /dev/null 2>&1
	(cd $GOPATH/src/$2 && git rev-list -n 1 $1)
}

md_print() {
	# alas this only works for github
	local url=https://$1
	local rc=$url/commit/$2
	local lc=$url/commit/$3
	echo "| " $rc " | " $lc " |"
}

echo "| version in docker/engine | version in cli |"
echo "|---|---|"
for P in $(grep -vE '^#|^$' vendor.conf | awk '{print $1}'); do
	V=$(grep -E "^$P[[:space:]]" vendor/github.com/docker/docker/vendor.conf | awk '{print $2}')
	[ -z "$V" ] && continue
	LV=$(grep -E "^$P[[:space:]]" vendor.conf | awk '{print $2}')
	[ "$V" = "$LV" ] && continue
	# versions might differ
	V=$(get_sha $V $P)
	LV=$(get_sha $LV $P)
	[ "$V" = "$LV" ] && continue
	# versions differ
	md_print $P $V $LV
done
```
and the results (alas links only work for github.com packages)

| version in docker/engine | version in cli |
|---|---|
|  https://github.com/containerd/containerd/commit/9754871865f7fe2f4e74d43e2fc7ccd237edcbce  |  https://github.com/containerd/containerd/commit/bb0f83ab6eec47c3316bb763d5c20a82c7750c31  |
|  https://github.com/containerd/continuity/commit/004b46473808b3e7a4a3049c20e4376c91eb966d  |  https://github.com/containerd/continuity/commit/d8fb8589b0e8e85b8c8bbaa8840226d0dfeb7371  |
|  https://github.com/containerd/typeurl/commit/a93fcdb778cd272c6e9b3028b2f42d813e785d40  |  https://github.com/containerd/typeurl/commit/f6943554a7e7e88b3c14aad190bf05932da84788  |
|  https://github.com/gogo/googleapis/commit/08a7655d27152912db7aaf4f983275eaf8d128ef  |  https://github.com/gogo/googleapis/commit/b23578765ee54ff6bceff57f397d833bf4ca6869  |
|  https://github.com/gogo/protobuf/commit/1adfc126b41513cc696b209667c8656ea7aac67c  |  https://github.com/gogo/protobuf/commit/636bf0302bc95575d69441b25a2603156ffdddf1  |
|  https://github.com/gorilla/context/commit/1ea25387ff6f684839d82767c1733ff4d4d15d0a  |  https://github.com/gorilla/context/commit/08b5f424b9271eedf6f9f0ce86cb9396ed337a42  |
|  https://github.com/gorilla/mux/commit/0eeaf8392f5b04950925b8a69fe70f110fa7cbfc  |  https://github.com/gorilla/mux/commit/e3702bed27f0d39777b0b37b664b6280e8ef8fbf  |
|  https://github.com/matttproud/golang_protobuf_extensions/commit/3247c84500bff8d9fb6d579d800f20b3e091582c  |  https://github.com/matttproud/golang_protobuf_extensions/commit/c12348ce28de40eed0136aa2b644d0ee0650e56c  |
|  https://github.com/Microsoft/go-winio/commit/97e4973ce50b2ff5f09635a57e2b88a037aae829  |  https://github.com/Microsoft/go-winio/commit/78a084671df137c2acfcacaa730d7e7dc285ac39  |
|  https://github.com/Microsoft/hcsshim/commit/5b3eff572681588b6ce3df295d3d23b72f053f32  |  https://github.com/Microsoft/hcsshim/commit/44c060121b68e8bdc40b411beba551f3b4ee9e55  |
|  https://github.com/opencontainers/runc/commit/96ec2177ae841256168fcf76954f7177af9446eb  |  https://github.com/opencontainers/runc/commit/20aff4f0488c6d4b8df4d85b4f63f1f704c11abd  |
|  https://github.com/opencontainers/runtime-spec/commit/5684b8af48c1ac3b1451fa499724e30e3c20a294  |  https://github.com/opencontainers/runtime-spec/commit/4e3b9264a330d094b0386c3703c5f379119711e8  |
|  https://github.com/pkg/errors/commit/645ef00459ed84a119197bfb8d8205042c6df63d  |  https://github.com/pkg/errors/commit/839d9e913e063e28dfd0e6c7b7512793e0a48be9  |
|  https://github.com/spf13/pflag/commit/583c0c0531f06d5278b7d917446061adc344b5cd  |  https://github.com/spf13/pflag/commit/4cb166e4f25ac4e8016a3595bbf7ea2e9aa85a2c  |
|  https://golang.org/x/sys/commit/ac767d655b305d4e9612f5f6e33120b9176c4ad4  |  https://golang.org/x/sys/commit/1b2967e3c290b7c545b3db0deeda16e9be4f98a2  |
|  https://google.golang.org/genproto/commit/694d95ba50e67b2e363f3483057db5d4910c18f9  |  https://google.golang.org/genproto/commit/02b4e95473316948020af0b7a4f0f22c73929b0e  |
|  https://gotest.tools/commit/b6e20af1ed078cd01a6413b734051a292450b4cb  |  https://gotest.tools/commit/1083505acf35a0bd8a696b26837e1fb3187a7a83  |

**Pull request merged**
