### PR TITLE
 Add bash completion for `docker trust` commands

### PR DESCRIPTION
**Pull request by albers**
This adds bash completion for #472.

This should go into 17.10.0 because the feature is present in that release.

### CODE REVIEW

**Comment by thaJeztah** [comment]
IIRC, we marked these commands "experimental" (which is a bit tricky, because it's a client-side only feature, so we don't currently hide them). 

I don't see a real harm in including them in the completion scripts (as 17.10 is an edge release, so no long-term consequences)

@riyazdf PTAL

**Comment by albers** [comment]
@thaJeztah The commands are only considered in bash completion if the CLI runs against an experimental server.

**Comment by riyazdf** [comment]
awesome, thanks @albers!  I am not familiar with how bash completion works so it'd be best if someone else can provide review/approval here.

**Comment by thaJeztah** [comment]
ah, yes, I forgot for a minute we added the check for experimental here as well 👍

**Pull request merged**
