### PR TITLE
Update docker dependency for pkg/term

### PR DESCRIPTION
**Pull request by crosbymichael**
We need the `pkg/term` dep from docker with OPOST added to the MakeRaw
call in order for the new runc 1.0 integration to work properly.

Signed-off-by: Michael Crosby <crosbymichael@gmail.com>

### CODE REVIEW

**Comment by crosbymichael** [comment]
Quickly hold off on this, i need to make one more update to the non-cgo version of the term package to fix static builds

**Comment by tianon** [comment]
https://github.com/moby/moby/pull/33128 merged! :smile: :tada:

**Comment by crosbymichael** [comment]
Ok, updated this to the latest docker after the update pr is merged.  This is ready for review and merge.  Sorry about the wait

**Comment by mlaventure** [comment]
```
Stderr: vendor/github.com/docker/docker/api/types/registry/registry.go:8:2: cannot find package "github.com/docker/distribution/manifest/manifestlist" in any of:
```

There seems to be an issue with vendoring

**Comment by crosbymichael** [comment]
@mlaventure what??? ;) updated

**Pull request merged**
