### PR TITLE
Fix json formating in dockerd docs

### PR DESCRIPTION
**Pull request by BastianHofmann**
**- What I did**
Fix minor JSON formating issue.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks for your contribution! The changes in this PR look good to me, but can you [sign-off your commit](https://github.com/docker/cli/blob/master/CONTRIBUTING.md#sign-your-work), otherwise the CI validation will fail. 

You can use the instructions that @GordonTheTurtle provided above, but let me know if you need help 👍

**Comment by thaJeztah** [comment]
I see you added another change; can you squash those commits? I think the changes are small enough to be in a single commit (some information about rebasing/squashing can be found in the contributors guide; https://docs.docker.com/opensource/workflow/work-issue/#pull-and-rebase-frequently)

**Comment by BastianHofmann** [comment]
Sorry for the wait guys. Commits should be squashed and signed now.

**Comment by thaJeztah** [comment]
And 🎉 congratulations with your first contribution to this repository 👍

**Pull request merged**
