### PR TITLE
docs: rename reference docs to "object_action"

### PR DESCRIPTION
**Pull request by dvdksn**
- carries, closes #2389
- relates to https://github.com/docker/docs/pull/19045

**- What I did**

Making sure there's only 1 canonical markdown file for each command. In the documentation repository, I'll add redirects for each command, and update titles to mention both variants.

e.g., redirect docker build to docker image build

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
I'll give it a try if we can make the changes show up as "move" in stead of "delete -> new file", so that (with a bit of luck) we can better preserve history.

So don't merge yet (but thanks so much for working on this!! changes look good)

**Comment by dvdksn** [comment]
hi @thaJeztah I changed the approach here and it should preserve history better now:

1. In the first commit I deleted the stub files which didn't have any content.
2. In the second commit I `git mv` the "golden" files and renamed them to use the canonical name.

If you check the diff for the 2nd commit it looks OK a6774de6827624db258915a61246fec0808d8a40

**Comment by dvdksn** [comment]
Hmm, yeah we don't need them at all in the docs, but regenerating `mddocs` would recreate those stubs, so let me commit the "empty" generated stubs just so they're there and we don't cause any trouble for someone the next time they want to regenerate markdown.

**Review by thaJeztah — APPROVED** [review]
LGTM

@crazy-max PTAL

**Comment by dvdksn** [comment]
snuck in an extra commit fixing a link to an anchor that doesn't exist and isn't needed 🙈

**Review by sam-thibault — APPROVED** [review]
lgtm

**Comment by thaJeztah** [comment]
Thanks! Let's bring this one in 👍

**Comment by thaJeztah** [comment]
We may have to check if there's old docs PRs that now fail, and need a carry (or "close"). If you have some time (not urgent) to check, that'd be great, @dvdksn

**Pull request merged**
