### PR TITLE
vendor: update moby to ed7b6428

### PR DESCRIPTION
**Pull request by tonistiigi**
Brings in https://github.com/moby/moby/pull/36663

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by seemethere** [comment]
This is needed to unblock us for the release of `18.04.0-ce-beta1`

**Comment by tiborvass** [comment]
LGTM

**Comment by andrewhsu** [comment]
Oops, hang on...

**Comment by andrewhsu** [comment]
Sorry for confusion, stuff looks good for this PR's vendor of moby/moby changes. Was waiting for the docker-ce 18.04 verification as well.

**Pull request merged**
