### PR TITLE
info: print errors to stderr

### PR DESCRIPTION
**Pull request by cpuguy83**
Errors always need to go to stderr.
This also fixes a test in moby/moby's integration-cli which is checking
to see if errors connecting to the daemon are output on stderr.

### CODE REVIEW

**Comment by thaJeztah** [comment]
Tests were failing because the `.golden` files needed to be updated; I pushed the test-updates to this branch

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@silvin-lubecki @StefanScherer PTAL

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Pull request merged**
