### PR TITLE
Bump golang 1.12.6

### PR DESCRIPTION
**Pull request by tao12345666333**
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>

**- What I did**
go1.12.6 (released 2019/06/11) includes fixes to the compiler, the linker,
the go command, and the <code>crypto/x509</code>, <code>net/http</code>, and
<code>os</code> packages. See the<a href="https://github.com/golang/go/issues?q=milestone%3AGo1.12.6">Go 1.12.6 milestone</a> on our issue tracker for details.

https://github.com/golang/go/compare/go1.12.5...go1.12.6

**- Description for the changelog**

bump golang 1.12.6

### CODE REVIEW

**Comment by tao12345666333** [comment]
need rebuild.

**Comment by thaJeztah** [comment]
Triggered a rebuild; the golang-cross image should be available now as well

**Comment by thaJeztah** [comment]
ping @vdemeester @silvin-lubecki

**Comment by tao12345666333** [comment]
thanks all.

**Pull request merged**
