### PR TITLE
fix innocuous data-race when config.Load called in parallel

### PR DESCRIPTION
**Pull request by coryb**
Locking was removed in https://github.com/docker/cli/pull/3025 which allows for parallel calls to config.Load to modify global state. The consequence in this case is innocuous, but it does trigger a `DATA RACE` exception when tests run with `-race` option.

### CODE REVIEW

**Comment by thaJeztah** [comment]
I recall we reverted it after a post-merge review, and we thought it wasn't needed. But the context load code is overly complicated with various conditions, so it doesn't surprise me it was needed after all 😁

**Review by thaJeztah — APPROVED** [review]
LGTM

@tonistiigi PTAL

**Review by crazy-max — APPROVED** [review]
Also encountered this one in a test suite.

**Comment by thaJeztah** [comment]
Yes, let's get this one in (we can probably remove this stuff after the next release)

**Pull request merged**
