### PR TITLE
Cleaned up formatting/typesetting.

### PR DESCRIPTION
**Pull request by KGB33**
Changed backticks to bold/italics, removed angle brackets.

Updated `cli/man/src/container/attach.md` to match formatting specified in #923
By changing in-line code i.e. backticks, to bold (for literals) and italics (for variables).

### CODE REVIEW

**Comment by KGB33** [comment]
I tested out the example and ran into an error:

```bash
ID=$(sudo docker run -d fedora /usr/bin/top -b)
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "/usr/bin/top": stat /usr/bin/top: no such file or directory: unknown.
```

Changing fedora to ubuntu solved the issue without changing it too much. I also pinned the ubuntu tag to help prevent another issue from happening in the future.

**Review by StefanScherer — COMMENTED** [review]
Thanks @KGB33 for the contribution.
Could you explain why the formatting change is needed? 
I can see that we have many similar man pages and they look good to me as they are. 🤔 

Indeed, the `fedora` image does not contain `top` command, but eg. `alpine` does or as you mentioned the `ubuntu` image as well.

**Comment by KGB33** [comment]
I changed the formatting to match what was discribed in Issue #923. 

This is a very small PR, If the formatting issues that #923 discribes is still the correct I'd be happy to update more of the man pages.

**Review by StefanScherer — APPROVED** [review]
Thank you @KGB33 for your contribution.
Thanks for the explanation, yes making small PR's make sense.
LGTM

**Review by thaJeztah — APPROVED** [review]
LGTM

thanks!

**Pull request merged**
