### PR TITLE
update/remove various tests and options related to kubernetes support

### PR DESCRIPTION
**Pull request by thaJeztah**
- Follow up to https://github.com/docker/cli/pull/3139
- Addresses https://github.com/docker/cli/issues/2967

-----

### update/remove various tests and options related to kubernetes support

Remove various tests and utilities related to testing kubernetes support

Also removing the `Kubernetes` and `DefaultStackOrchestrator` from `CreateOptions`
and `UpdateOptions`, instead updating the flags to not be bound to a variable.

This might break some consumers of those options, but given that they've become
non-functional, that's probably ok (otherwise they may ignore the deprecation
warning and end up with non-functional code).

### CODE REVIEW

**Comment by thaJeztah** [comment]
Sigh.. `go modules` are you okay??

```
+ go mod tidy -modfile=vendor.mod
go: github.com/creack/pty@v1.1.11: reading github.com/creack/pty/go.mod at revision v1.1.11: unknown revision v1.1.11
```

**Comment by thaJeztah** [comment]
It really exists: https://github.com/creack/pty/blob/v1.1.11/go.mod

**Comment by thaJeztah** [comment]
Sight... and now its failing on another dependency

```
#14 1.112 + go mod tidy -modfile=vendor.mod
#14 148.0 go: github.com/theupdateframework/notary@v0.7.1-0.20210315103452-bf96a202a09a requires
#14 148.0 	github.com/go-sql-driver/mysql@v1.5.0: reading github.com/go-sql-driver/mysql/go.mod at revision v1.5.0: unknown revision v1.5.0
```

**Review by ndeloof — APPROVED** [review]

**Comment by thaJeztah** [comment]
Thanks for reviewing; let's bring this one in as well 👍

**Pull request merged**
