### PR TITLE
Remove "context" from context store interfaces function names

### PR DESCRIPTION
**Pull request by simonferquel**
Based on #1836
This was originally suggested by @thaJeztah in https://github.com/docker/cli/pull/1836#discussion_r276618400.

This PR is just basically a bunch of find/replace in the project files, wich should either happen before we release 19.03 or never.

### CODE REVIEW

**Comment by thaJeztah** [comment]
some linting errors

```
cli/command/context/inspect.go:1::warning: file is not gofmted with -s (gofmt)
cli/command/context/inspect.go:1::warning: file is not goimported (goimports)
cli/context/store/store.go:45:1:warning: comment on exported type StorageInfoProvider should be of the form "StorageInfoProvider ..." (with optional leading article) (golint)
Exited with code 1

**Comment by thaJeztah** [comment]
@silvin-lubecki @vdemeester PTAL

**Comment by simonferquel** [comment]
Linting errors fixed

**Comment by thaJeztah** [comment]
Let's merge! I briefly spoke with @chris-crone and he's aware some renaming is needed. It's a bit of a pain, but better have it done now than in future 🤗

**Pull request merged**
