### PR TITLE
Fix typo in 3.6 schema ID

### PR DESCRIPTION
**Pull request by shin-**
**- What I did**

Changed a 5 to a 6

**- How I did it**

M-x butterfly

**- How to verify it**
```
$ test -z "$(grep '3\.5' cli/compose/schema/data/config_schema_v3.6.json)"
$ echo $?
0
$ test -z "$(grep '3\.6' cli/compose/schema/data/config_schema_v3.6.json)"
$ echo $?
1
```

**- A picture of a cute animal (not mandatory but encouraged)**

image

### CODE REVIEW

**Comment by thaJeztah** [comment]
```
make[1]: Entering directory '/go/src/github.com/docker/cli'
go generate github.com/docker/cli/cli/compose/schema
can't load package: package github.com/docker/cli/cli/compose/schema: found packages main (bindata.go) and schema (schema.go) in /go/src/github.com/docker/cli/cli/compose/schema
make[1]: ***

**Comment by dnephin** [comment]
Thanks for the fix. You can generate it with the correct package name using `go generate ./cli/compose/schema`

**Comment by thaJeztah** [comment]
rebased and re-generated

**Comment by shin-** [comment]
Thanks @thaJeztah :1st_place_medal:

**Pull request merged**
