### PR TITLE
Bump Go to 1.9.3

### PR DESCRIPTION
**Pull request by thaJeztah**
still needs https://github.com/docker/golang-cross/pull/3 to be merged, and a new version built on Docker Hub so that we can update the Dockerfile.cross

release notes: https://golang.org/doc/devel/release.html#go1.9.minor

full diff: https://github.com/golang/go/compare/go1.9.2...go1.9.3

ping @vdemeester @dnephin

### CODE REVIEW

**Comment by dnephin** [comment]
Needs #826 to fix failures

https://hub.docker.com/r/dockercore/golang-cross/builds/bimnbt6yubifkjsi4rzmz2n/

**Comment by thaJeztah** [comment]
don't merge yet, I have to update https://hub.docker.com/r/dockercore/golang-cross/tags/ as well

**Comment by dnephin** [comment]
Just tagged `dockercore/golang-cross:1.9.3`

**Comment by thaJeztah** [comment]
Thanks! Updated 👍

**Comment by dnephin** [comment]
Thanks!

**Pull request merged**
