### PR TITLE
search: remove client-side default for --limit

### PR DESCRIPTION
**Pull request by thaJeztah**
- [x] depends on https://github.com/moby/moby/pull/43380
- [x] depends on https://github.com/docker/cli/pull/3486

The daemon (and registry) already have a default limit. This patch
removes the default from the client side, to not duplicate setting
these defaults.

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Interesting; looks like a flaky test, but if it's all mocked... how?

```
--- FAIL: TestContainerListNoTrunc (0.00s)
    list_test.go:198: assertion failed: 
        --- expected
        +++ actual
        @@ -1,4 +1,4 @@
        -CONTAINER ID   IMAGE            COMMAND   CREATED                  STATUS        PORTS     NAMES
        -container_id   busybox:latest   "top"     Less than a second ago   Up 1 second             c1
        -container_id   busybox:latest   "top"     Less than a second ago   Up 1 second             c2,foo/bar
        +CONTAINER ID   IMAGE            COMMAND   CREATED        STATUS        PORTS     NAMES
        +container_id   busybox:latest   "top"     1 second ago   Up 1 second             c1
        +container_id   busybox:latest   "top"     1 second ago   Up 1 second             c2,foo/bar
```

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/3504 to fix the test

**Review by rumpl — APPROVED** [review]
LGTM!

**Comment by thaJeztah** [comment]
thx! had some other changes and kept having to juggle branches 😂

**Comment by thaJeztah** [comment]
We need to look into this one; looks like it's actually became less reliable (as can be seen in flakiness in CI);

```
--- FAIL: TestInitTtySizeErrors (0.10s)
    tty_test.go:29: assertion failed: 
        --- expectedError
        +++ →
        @@ -1,2 +1 @@
        -failed to resize tty, using default size
```

**Pull request merged**
