### PR TITLE
Revert "Change sshfs by cloudstor on Installing and using a plugin"

### PR DESCRIPTION
**Pull request by mstanleyjones**
Reverts docker/cli#493

### CODE REVIEW

**Comment by friism** [comment]
lgtm thx

**Comment by mstanleyjones** [comment]
Yeah I know I need to sign the commit. I'll do it as soon as I can.

**Comment by mstanleyjones** [comment]
Now signed.

**Comment by mstanleyjones** [comment]
Why aren't the tests running? @tiborvass

**Comment by tiborvass** [comment]
@mstanleyjones still not signed. You forgot to push maybe?

**Comment by mstanleyjones** [comment]
I didn't realize the branch was on this repo and not my fork! 😊

**Comment by mstanleyjones** [comment]
I'm going to merge this. 👼

**Pull request merged**
