### PR TITLE
remove redundant code in update action in api call

### PR DESCRIPTION
**Pull request by allencloud**
remove redundant code in update action in api call

Signed-off-by: allencloud <allen.sun@daocloud.io>

### CODE REVIEW

**Comment by allencloud** [comment]
Thanks for your feedback, and I have rebased to the master. @gdevillele 
While I am afraid no CI triggered. Still have no idea about the reason.

**Comment by gdevillele** [comment]
Thank you @allencloud for reporting this. 
I just checked and it is my mistake, I haven't setup the CI correctly for PRs.
I am going to fix this ASAP.

**Comment by gdevillele** [comment]
@allencloud sorry for the inconvenience. It should be fixed now. Would you mind pushing against your PR branch again, please?

**Comment by allencloud** [comment]
Done, Thanks a lot for your work. @gdevillele

**Comment by dnephin** [comment]
I think I'm missing some context. Why is this redundant code?

**Comment by allencloud** [comment]
@dnephin Here is my thought.
Since the functions like `func (cli *Client) NodeUpdate(...) error` just return error, not other type instances. Then we could ignore the returned response. If we ignore the response we could ignore to call `ensureReaderClosed(resp)` as well.

**Comment by dnephin** [comment]
Even if we ignore the response object it is still allocated. `ensureReaderClosed()` seems to be about closing the response body so that the transport can re-use the connection. That still seems relevant to me in these cases.

**Comment by gdevillele** [comment]
Thanks @dnephin. I had second thoughts after taking a closer look to `ensureReaderClosed`. I am not familiar with `net/http` mechanics regarding connection re-use. If response struct deallocation doesn't allow connection re-use, then yes, we should discard this PR.

**Comment by gdevillele** [comment]
Reading the body entirely and then closing it is necessary for the underlying connection to be re-used (when a Keep-Alive header is returned for example)
I think we should discard this PR.

**Comment by dnephin** [comment]
Thanks @allencloud  for the PR. 

It sounds like we do need these calls. If you believe we are wrong please do let us know!

**Pull request closed without merging**
