### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by derskeal**
**- What I did**
Fixed a typo
**- How I did it**
By pressing keys on my keyboard
**- How to verify it**
Read the diff
**- Description for the changelog**

Fixed a typo in option description

### CODE REVIEW

**Comment by tiborvass** [comment]
@derskeal thanks! The part of the docs you changed come from `cli/command/network/create.go` so you should update that too.

**Comment by derskeal** [comment]
@tiborvass The file `cli/command/network/create.go` does not have the reference docs in it.

**Comment by thaJeztah** [comment]
@derskeal sorry for the confusion; what @tiborvass meant is the description of the flag itself (as it's set in the source-code); which can be found on this line: https://github.com/docker/cli/blob/f2424bd3753af96ab2be741ae55af11841a8f0bd/cli/command/network/create.go#L71

The Markdownfile is currently only used to read on GitHub, but the flag description in the documentation on docs.docker.com is generated from the source code, so changing the Markdown file won't fix it in the actual documentation 😅

**Comment by derskeal** [comment]
Thanks! @thaJeztah @tiborvass.

**Comment by thaJeztah** [comment]
ping @tiborvass @silvin-lubecki PTAL

**Pull request merged**
