### PR TITLE
Compose: Improve error messages when resource create/update fails

### PR DESCRIPTION
**Pull request by dnephin**
Previously secret update errors looked like this:

> Error response from daemon: rpc error: code = 3 desc = only updates to Labels are allowed

which do not provide enough details for a user to understand what failed.

Also removes some unnecessary conditions in `deployServices()`

### CODE REVIEW

**Comment by dnephin** [comment]
Added another commit which uses a map instead of a switch/case for the compose loader transform

**Comment by aaronlehmann** [comment]
The changes to error messages LGTM. Are the rest of the changes unrelated cleanups?

**Comment by dnephin** [comment]
Yes

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
