### PR TITLE
fixes #1441 set default schema to tcp for docker host

### LINKED ISSUE #1441: docker -H :2375 can't work now
**Description**
While in "Docker version 17.12.0-ce, build c97c6d6", the scheme tcp in "-H" is not required, docker cli will add it Automatically. But in docker master, it will raise an error.

Is this feature removed in plan or just an error?

**Steps to reproduce the issue:**
1. build/docker -H 172.17.254.15:8410 ps

**Describe the results you received:**
parse 172.17.254.15:8410: first path segment in URL cannot contain colon

**Describe the results you expected:**
CONTAINER ID        IMAGE               COMMAND                   CREATED             STATUS              PORTS               NAMES
3655addd70cf        testredis:latest    "docker-entrypoint.s…"   12 hours ago        Up 12 hours         6379/tcp            testredis.1.be7884xqcywuwdo3b86mpmozb

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**
root@dockerdemo:~/gocode/src/github.com/docker/cli# build/docker version
Client:
 Version:           unknown-version
 API version:       1.39
 Go version:        devel +30c1ed7 Sat Oct 6 00:02:35 2018 +0000
 Git commit:        b9a1a21
 Built:             Fri Oct 12 01:42:29 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          dev
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.11.1
  Git commit:       5d82d77
  Built:            Thu Oct 11 02:41:04 2018
  OS/Arch:          linux/amd64
  Experimental:     true

**Output of `docker info`:**
Containers: 30
 Running: 20
 Paused: 0
 Stopped: 10
Images: 376
Server Version: dev
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: nlcdk6e11zro6x4hbw55vafiq
 Is Manager: true
 ClusterID: xkuby3a03f29z41n2biii2mc0
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 172.17.254.34
 Manager Addresses:
  172.17.254.34:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9f2e07b1fc1342d1c48fe4d7bbb94cb6d1bf278b
runc version: 69663f0bd4b60df09991c08812a60108003fa340
init version: fec3683
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-105-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.859GiB
Name: dockerdemo
ID: DYEJ:3IVL:NK53:YFIS:AJMT:VOGT:2HIB:7VZS:GN5A:FFP5:NIAY:QXDS
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: API is accessible on http://0.0.0.0:8410 without encryption.
         Access to the remote API is equivalent to root access on the host. Refer
         to the 'Docker daemon attack surface' section in the documentation for
         more information: https://docs.docker.com/engine/security/security/#docker-daemon-attack-surface
WARNING: No swap limit support

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Aliyun ECS

### PR DESCRIPTION
**Pull request by lifubang**
Signed-off-by: Lifubang <lifubang@acmcoder.com>
**- What I did**
Please see #1441 
There is a traditional command "docker -H :2375 ps" in docker cli, but in master, it can't work now.
Is this feature removed in plan or just an error?

**- How I did it**
I think this may be a bug after merge #1014 
add case ssh to dopts.ParseHost, together with all other schema.

**- How to verify it**
see #1441

**- Description for the changelog**
set default schema to tcp for docker host param when there is no schema

**- A picture of a cute animal (not mandatory but encouraged)**
p08ehdk zh d s d426fzw

### CODE REVIEW

**Comment by lifubang** [comment]
I have update a more reasonable schema parse method.
ping @AkihiroSuda @cpuguy83 PTAL

**Comment by lifubang** [comment]
> Code looks good to me, thank you! But I wonder if we can add a regression test here on this feature. 

@silvin-lubecki Thank you for your review.
It's a good idea to add a test case which can avoid such error.

**Comment by lifubang** [comment]
Shall we need to merge to 18.09? Otherwise the version 18.09 will become the only version which doesn't support default host schema.

**Comment by thaJeztah** [comment]
@lifubang yes, I had this one on my list to backport to 18.09

**Comment by cpuguy83** [comment]
Can you open a pr to the release branch?

**Comment by thaJeztah** [comment]
@cpuguy83 almost done 😅

**Comment by cpuguy83** [comment]
haha, posting at the same time.

**Comment by thaJeztah** [comment]
backport is up https://github.com/docker/cli/pull/1454

**Pull request merged**
