### PR TITLE
Revendor dependencies

### PR DESCRIPTION
**Pull request by thaJeztah**
As noticed in https://github.com/docker/cli/pull/312, the vendor directory was out of date. Haven't found yet which commit introduced this.

Re-ran `vndr` on master

ping @mlaventure @vdemeester @dnephin PTAL

### CODE REVIEW

**Comment by thaJeztah** [comment]
Ah - I was going back some commits in this repository to see what caused this... turns out it's due to a change in vndr :smile: https://github.com/LK4D4/vndr/commit/9909bb2b8a0b7ea464527b376dc50389c90df587 (https://github.com/LK4D4/vndr/pull/50)

**Comment by tiborvass** [comment]
LGTM

**Comment by tonistiigi** [comment]
LGTM (we should pin to a specific commit of vndr in follow up)

**Comment by thaJeztah** [comment]
Yes, per our discussion on Slack, we should look into pinning `vndr`, I'll have a look if I can come up with something, or call for help if needed 👍

**Pull request merged**
