### PR TITLE
using nature sort secrets and configs in cli

### PR DESCRIPTION
**Pull request by allencloud**
Signed-off-by: allencloud <allen.sun@daocloud.io>

**- What I did**
1. sort secrets and configs in cli

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by dnephin** [comment]
Although some tests do need to be updated

**Comment by aaronlehmann** [comment]
I think this should use the "natural sort" like #302. ping @ripcurld0

**Comment by allencloud** [comment]
Thanks for your feedback, I will do a change. @aaronlehmann 
In addition, @dnephin , I think this PR fails to trigger the CI.

**Comment by dnephin** [comment]
hmm, not sure why that is. Maybe cirlceci was having issues?

Have you setup circleci on your fork? I think that can cause problems sometimnes

**Comment by yuexiao-wang** [comment]
@allencloud  This PR needs to be rebased

**Comment by aaronlehmann** [comment]
CI is failing

```
cli/command/config/ls_test.go:80: use of package assert without selector
cli/command/config/ls_test.go:81: use of package assert without selector
```

**Comment by allencloud** [comment]
Thanks for your feedback. @aaronlehmann 
I will turn to this PR in few days. Sorry for the delay. ☀️

**Comment by vdemeester** [comment]
@allencloud ping 👼

**Comment by allencloud** [comment]
Sorry for the delay. And I have updated this PR to use natural sort to sort docker cli config/secret ls output. PTAL @dnephin @aaronlehmann @vdemeester

**Pull request merged**
