### PR TITLE
docs: move doc generation scripts to subdir

### PR DESCRIPTION
**Pull request by dvdksn**
Signed-off-by: David Karlsson <david.karlsson@docker.com>

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Review by thaJeztah — CHANGES_REQUESTED** [review]
oh, actually; could you squash the commits, @dvdksn ?

**Comment by dvdksn** [comment]
> oh, actually; could you squash the commits, @dvdksn ?

done!

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
