### PR TITLE
Change sshfs by cloudstor on Installing and using a plugin

### PR DESCRIPTION
**Pull request by jmaitrehenry**
Signed-off-by: Julien Maitrehenry <julien.maitrehenry@me.com>

**- What I did**
Update the documentation page about plugins
See for the original PR: https://github.com/docker/docker.github.io/pull/4294

**- Description for the changelog**
Replace sshfs plugin installation and usage example by cloudstor

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by mstanleyjones** [comment]
@ddebroy PTAL

**Comment by ddebroy** [comment]
LGTM .. also adding @friism as FYI

**Comment by friism** [comment]
I'm not sure I think cloudstor is a good example to use in the plugin sample docs:

 * It only works on AWS/Azure (which means that trying it out requires much more setup)
 * It's more complicated, which makes it less useful as an example because the user also has to grok a bunch of AWS-specifics that are unrelated to the samples purpose of teaching people about plugins

**Comment by mstanleyjones** [comment]
:( I'll revert and we can continue discussion here or maybe @jmaitrehenry can do a follow-on PR.

**Comment by jmaitrehenry** [comment]
Where could we add documentation about cloudstor?

First idea: put it with docker for Azure/AWS because it's only for those two but, as @ddebroy already mention, it comes pre-installed / pre-configured on those products

Second idea: add the information on the plugin page here: https://store.docker.com/community/images/docker4x/cloudstor

Third idea: create a tutorial on how create a docker cluster with swarm and cloudstor on Azure here: https://docs.docker.com/samples/ but why we want to create a cluster on Azure without using Docker for Azure?

Fourth: Open source the cloudstor plugin and add documentation inside the plugin repository but it's not for now I think.

**Pull request merged**
