### PR TITLE
Fix bash completion for "docker swarm"

### PR DESCRIPTION
**Pull request by muicoder**
"docker swarm" auto-completion is invalid.

### CODE REVIEW

**Comment by albers** [comment]
Can you please explain why you want to remove support for `docker swarm` completion?

**Comment by muicoder** [comment]
When I set DOCKER_HIDE_LEGACY_COMMANDS=true, swarm is not available, “swarm” is placed in legacy_commands, it should not be in management_commands?

**Comment by albers** [comment]
Ah yes, you are right. `docker swarm` is a management command, not a legacy command.
Thanks very much for your fix.

**Comment by albers** [comment]
@muicoder Please sign your commit.

**Pull request merged**
