### PR TITLE
Prefix engine repo with store

### PR DESCRIPTION
**Pull request by dhiltgen**
The official access point for the Q3 engine images will
be prefixed by store.

Signed-off-by: Daniel Hiltgen <daniel.hiltgen@docker.com>

### CODE REVIEW

**Comment by tescherm** [comment]
will do

**Comment by thaJeztah** [comment]
> docker.io/docker will still be valid right ? (so that 18.03 cli will, in mid-term, still be able to init, …)

Ah, had the same question, but notice I didn't post it; is this an alias, or is the repository being moved?

**Comment by dhiltgen** [comment]
> `docker.io/docker` will still be valid right ? (so that 18.03 cli will, in mid-term, still be able to `init`, …)

This prefix wont work through the license entitlement flow on UCP so Enterprise customers wont get access to the repo correctly.  The `/store/` prefix is needed to trigger the proper entitlement checks on the back-end.

**Comment by dhiltgen** [comment]
> Ah, had the same question, but notice I didn't post it; is this an alias, or is the repository being moved?

It is an alias on the hub/store side to trigger the entitlement checking flow.

**Comment by thaJeztah** [comment]
oh, needs a rebase; let me carry so that we can move forward

**Comment by thaJeztah** [comment]
carried in https://github.com/docker/cli/pull/1368

**Comment by mavenugo** [comment]
Closing this as https://github.com/docker/cli/pull/1368 is merged

**Pull request closed without merging**
