### PR TITLE
vendor: github.com/docker/docker v26.0.0-rc1

### PR DESCRIPTION
**Pull request by vvoland**
full diff: https://github.com/docker/docker/compare/c70d7905fbd9...v26.0.0-rc1

Signed-off-by: Paweł Gronowski <pawel.gronowski@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like a test needs updating because of the `Updated` field now having `omit empty`. That change was backported to v25.0.x (but not yet released), so we may want to have a check how to best resolve that (to make it work on updated 25.0 versions as well 🤔)


```
=== FAIL: cli/command/image TestNewInspectCommandSuccess/simple-many (0.00s)
#20 55.00     inspect_test.go:87: assertion failed: 
#20 55.00         --- expected
#20 55.00         +++ actual
#20 55.00         @@ -6,5 +6,4 @@
#20 55.00                  "Parent": "",
#20 55.00                  "Comment": "",
#20 55.00         -        "Created": "",
#20 55.00                  "Container": "",
#20 55.00                  "ContainerConfig": null,
#20 55.00         @@ -30,5 +29,4 @@
#20 55.00                  "Parent": "",
#20 55.00                  "Comment": "",
#20 55.00         -        "Created": "",
#20 55.00                  "Container": "",
#20 55.00                  "ContainerConfig": null,
#20 55.00         
#20 55.00         
#20 55.00         You can run 'go test . -update' to automatically update testdata/inspect-command-success.simple-many.golden to the new expected value.'
#20 55.00         
```

**Comment by vvoland** [comment]
Related: https://github.com/moby/moby/pull/47450

**Comment by Benehiko** [comment]
For some reason I couldn't commit @vvoland's branch. Opened a new one here https://github.com/docker/cli/pull/4906

**Comment by vvoland** [comment]
Thanks! Let me close this one.

**Pull request closed without merging**
