### PR TITLE
✨ Add `-b` flag to `docker build` to allow building without a Dockerfile

### PR DESCRIPTION
**Pull request by david-martin**
**- What I did**

Added a new flag `-b` or `--base-image` to the `docker build` command.
This allows building of an image from a local dir or remote repo without
the need for a Dockerfile. This can be useful when using an 'on-build'
style image e.g. node:6-onbuild

**- How I did it**

Modified the build command to add the extra flag.
If a base-image is passed in, write a Dockerfile with that image as the
`FROM` image into the build context, then build the image.
These changes make use of existing code that writes a Dockerfile based
on stdin into the build context.

**- How to verify it**

Run the following command in the root of a golang app

```bash
docker build -b golang:1.8.1-onbuild .
```

e.g.

```
docker build -b golang:1.8.1-onbuild .
Sending build context to Docker daemon   57.9kB
Step 1 : FROM golang:1.8.1-onbuild
Step 1 : COPY . /go/src/app
 ---> Using cache
Step 1 : RUN go-wrapper download
 ---> Using cache
Step 1 : RUN go-wrapper install
 ---> Using cache
 ---> a72803679296
Successfully built a72803679296
```

To build a remote respository that doesn't have a Dockerfile:

```bash
docker build -b node:4-onbuild github.com/david-martin/nodejs-ex.git
Sending build context to Docker daemon  376.9kB
Step 1 : FROM node:4-onbuild
Step 1 : ARG NODE_ENV
 ---> Using cache
Step 1 : ENV NODE_ENV $NODE_ENV
 ---> Using cache
Step 1 : COPY package.json /usr/src/app/
 ---> Using cache
Step 1 : RUN npm install && npm cache clean
 ---> Using cache
Step 1 : COPY . /usr/src/app
 ---> 4edcd5007ad4
Removing intermediate container 13aa2c9da2ee
Successfully built 4edcd5007ad4
```

Note: this new flag conflicts with `-f` and passing a Dockerfile via
stdin. e.g.

```bash
docker build -f Dockerfile -b node:4-onbuild github.com/david-martin/nodejs-ex.git
Conflicting options: -f and -b
```

**- Description for the changelog**

Added `--base-image` argument to `docker build`

**- A picture of a cute animal (not mandatory but encouraged)**

http://i.imgur.com/spIXiOT.jpg

### CODE REVIEW

**Comment by thaJeztah** [comment]
Why not add the Dockerfile using `stdin`?

```bash
docker build . -f-<<EOF
FROM golang:1.8.1-onbuild
EOF
```

**Comment by david-martin** [comment]
Hi @thaJeztah,
there is no reason you couldn't use `stdin` for this. 
The idea behind having the arg is a shorthand way of producing an artifact from your source, without maintaining or knowing about Dockerfile syntax. 
All build logic is kept in your 'ONBUILD' steps of some other docker image. If you conform to a 'normal' application, you can produce a docker image in 1 line.

I'm OK if you decide this isn't part of the docker cli vision. I thought it might be a neat way of having some of the functionality of this tool https://github.com/openshift/source-to-image in docker.

**Comment by tonistiigi** [comment]
I'm -1 on this but as it was decided to deprecate onbuild in official images https://github.com/docker-library/docs/pull/911/files and the workaround is very simple, but as this is only a client side change I wouldn't object much if someone feels opposite.

**Comment by dnephin** [comment]
I agree with @thaJeztah it seems easy enough to do with dockerfile from stdin that it doesn't really warrant another flag.

It would be good to document this use of "dockerfile from stdin".

**Comment by thaJeztah** [comment]
> It would be good to document this use of "dockerfile from stdin".

Proposal for that enhancement was https://github.com/moby/moby/issues/27393, and implementation in https://github.com/moby/moby/pull/31236.

Looks like it still has a `docs/revisit` label, so needs documentation changes 😅

**Comment by thaJeztah** [comment]
Opened an issue for documentation; https://github.com/docker/docker.github.io/issues/3538

**Comment by david-martin** [comment]
Thanks for the feedback @thaJeztah @dnephin @tonistiigi.
Good to know that official`onbuild` images are being deprecated.
Is the `ONBUILD` instruction being deprecated too?
If it is, I wonder if that would leave a gap where that forces developers to update their Dockerfiles with extra instructions, and raises the barrier somewhat.

**Comment by tonistiigi** [comment]
> Is the ONBUILD instruction being deprecated too?

No

**Comment by cpuguy83** [comment]
Also -1 on this.
I'm going to close since it seems like the maintainers are in agreement that this is not something we want to take on.

Thanks for opening this up @david-martin.

**Comment by david-martin** [comment]
Thanks guys for the feedback

**Pull request closed without merging**
