### PR TITLE
UX: don't reverse progress-bars when rolling back

### PR DESCRIPTION
**Pull request by thaJeztah**
Commit https://github.com/moby/moby//commit/330a0035334871d92207b583c1c36d52a244753f (https://github.com/moby/moby/pull/31144) introduced "synchronous" service update and rollback, using progress bars to show current status for each task.

As part of that change, progress bars were "reversed" when doing a rollback, to indicate that status was rolled back to a previous state.

Reversing direction is somewhat confusing, as progress bars now return to their "initial" state to indicate it was "completed"; for an "automatic" rollback, this may be somewhat clear (progress bars "move to the right", then "roll back" if the update failed), but when doing a manual rollback, it feels counter-intuitive (rolling back is the _expected_ outcome).

This patch removes the code to reverse the direction of progress-bars, and makes progress-bars always move from left ("start") to right ("finished").

Before this patch
----------------------------------------

1. create a service with automatic rollback on failure

        $ docker service create --update-failure-action=rollback --name foo --tty --replicas=5 nginx:alpine
        9xi1w3mv5sqtyexsuh78qg0cb
        overall progress: 5 out of 5 tasks
        1/5: running   [==================================================>]
        2/5: running   [==================================================>]
        3/5: running   [==================================================>]
        4/5: running   [==================================================>]
        5/5: running   [==================================================>]
        verify: Waiting 2 seconds to verify that tasks are stable...

2. update the service, making it fail after 3 seconds

        $ docker service update --entrypoint="/bin/sh -c 'sleep 3; exit 1'" foo
        overall progress: rolling back update: 2 out of 5 tasks
        1/5: running   [==================================================>]
        2/5: running   [==================================================>]
        3/5: starting  [============================================>      ]
        4/5: running   [==================================================>]
        5/5: running   [==================================================>]

3. Once the service starts failing, automatic rollback is started; progress-bars now move in the reverse direction;

        overall progress: rolling back update: 3 out of 5 tasks
        1/5: ready     [===========>                                       ]
        2/5: ready     [===========>                                       ]
        3/5: running   [>                                                  ]
        4/5: running   [>                                                  ]
        5/5: running   [>                                                  ]

4. When the rollback is completed, the progressbars are at the "start" to indicate they completed;

        overall progress: rolling back update: 5 out of 5 tasks
        1/5: running   [>                                                  ]
        2/5: running   [>                                                  ]
        3/5: running   [>                                                  ]
        4/5: running   [>                                                  ]
        5/5: running   [>                                                  ]
        rollback: update rolled back due to failure or early termination of task bndiu8a998agr8s6sjlg9tnrw
        verify: Service converged

After this patch
----------------------------------------

Progress bars always go from left to right; also in a rollback situation;

After updating to the "faulty" entrypoint, task are deployed:

        $ docker service update --entrypoint="/bin/sh -c 'sleep 3; exit 1'" foo
        foo
        overall progress: 1 out of 5 tasks
        1/5:
        2/5: running   [==================================================>]
        3/5: ready     [======================================>            ]
        4/5:
        5/5:

Once tasks start failing, rollback is started, and presented the same as a regular
update; progress bars go from left to right;

        overall progress: rolling back update: 3 out of 5 tasks
        1/5: ready     [======================================>            ]
        2/5: starting  [============================================>      ]
        3/5: running   [==================================================>]
        4/5: running   [==================================================>]
        5/5: running   [==================================================>]
        rollback: update rolled back due to failure or early termination of task c11dxd7ud3d5pq8g45qkb4rjx

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by silvin-lubecki** [comment]
@thaJeztah linter is failing:
```
cli/command/service/progress/progress.go:381:105: `(*replicatedProgressUpdater).writeTaskProgress` - `rollback` is unused (unparam)
func (u *replicatedProgressUpdater) writeTaskProgress(task swarm.Task, mappedSlot int, replicas uint64, rollback bool) {
```

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
>  linter is failing:

Ah, dang. I separated this from the other PR, probably forgot to remove some things; I'll have a look

**Comment by thaJeztah** [comment]
Think it should be fixed now

**Review by chris-crone — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
@tiborvass @cpuguy83 ptal

**Comment by thaJeztah** [comment]
Rebased to get a fresh run of CI

**Pull request merged**
