### PR TITLE
adopt github.com/WeiZhang555/tabwriter to support non-Latin rune size

### PR DESCRIPTION
**Pull request by ndeloof**
closes https://github.com/docker/cli/issues/3421
also reported https://github.com/golang/go/issues/51650, maybe we will get a fix in standard library at some point?

**- What I did**
replaced golang's tabwrittter with github.com/WeiZhang555/tabwriter to support non-latin character width

**- How I did it**
replace imports (github.com/WeiZhang555/tabwriter is a fork from golang's tabwriter)

**- How to verify it**
`docker search twang2218`

**- Description for the changelog**
docker table output supports non-latin characters to compute column sizes

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Couple of things (just from a very cursory glance);

- the https://github.com/WeiZhang555/tabwriter package looks to be a fork of the stdlib tabwriter, but it's based on a version from 6 years ago; we should check if there's no fixes we're missing that were made since then; https://github.com/golang/go/commits/master/src/text/tabwriter/tabwriter.go)
- I see it originally used `golang.org/x/text/width`, but there was an issue with that, which made it switch to use `github.com/mattn/go-runewidth` - slightly wondering if that was a _bug_ in `golang.org/x/text` (and if so, if that either was fixed upstream, or if there's something to fix?)
- Overall, it would be nice if golang's own `text/tabwriter` would do this correct "out of the box' (or if out of scope for that, if this would be something that could be part of `golang.org/x/text`)

**Comment by ndeloof** [comment]
I've reported https://github.com/golang/go/issues/51650 to (maybe?) get some feedback on this regarding the standard library and see what would be the best option for this.

**Comment by rumpl** [comment]
`text/tabwriter` is frozen, no new features and bugfixes will get into it. It also doesn't support non-latin things and never will, I think it's a great candidate to remove and use something else that fixes our issues

**Comment by ndeloof** [comment]
working on https://github.com/docker/cli/pull/3568 as an alternative

**Pull request closed without merging**
