### PR TITLE
e2e: update notary certificates

### PR DESCRIPTION
**Pull request by crazy-max**
follow-up https://github.com/docker/cli/pull/4122#issuecomment-1484908622

**- What I did**

Update notary certificates for e2e tests and increase tests certificates duration to 10 years (3 years previously).

Also moves script to generate certificates to a dedicated Dockerfile to be sandboxed:

```
$ docker buildx bake e2e-gencerts
```

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
oh! fancy 😄 

LGTM (if CI is happy)

**Comment by thaJeztah** [comment]
If we need this for 20.10, we probably need to modify it a bit when backporting, but that's for a later concern (worst case, we just copy over the certs to that branch)

**Comment by crazy-max** [comment]
I can just have an extra commit with just the certs to ease backport if yo uwant?

**Comment by thaJeztah** [comment]
Whoop! All green; thank you!

**Pull request merged**
