### PR TITLE
fix: make options case-sensitive

### PR DESCRIPTION
**Pull request by beyazit**
**- What I did**
This pull request makes the options case-sensitive.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Thanks for working on this! I recall I left those TODO's as "TODO" because, while I think we _should_ make these case sensitive, changing this will be a breaking change for users that use the ("supported", but undocumented) options.

So before we change the behavior we may need to

- first mark these as "deprecated" for at least 1 release (adding a deprecation notice in [docs/deprecated.md](https://github.com/docker/cli/blob/v24.0.5/docs/deprecated.md))
- _possibly_ print a deprecation _warning_ if a user uses one of these options with a "non-standard" case (but still make them work)

After those changes have shipped in a release, we can proceed with the changes in this PR to change the warning into an error.

**Comment by thaJeztah** [comment]
Oh! It appears your commit message is missing a DCO sign-off,
causing the DCO check to fail.

We require all commit messages to have a `Signed-off-by` line with your name
and e-mail (see ["Sign your work"](https://github.com/moby/moby/blob/v20.10.11/CONTRIBUTING.md#sign-your-work)
in the CONTRIBUTING.md in this repository), which looks something like:

```
Signed-off-by: YourFirsName YourLastName <yourname@example.org>
```

There is no need to open a new pull request, but to fix this (and make CI pass),
you need to _amend_ the commit(s) in this pull request, and "force push" the amended
commit.

Unfortunately, it's not possible to do so through GitHub's web UI, so this needs
to be done through the git commandline.

You can find some instructions in the output of the DCO check (which can be found
in the "checks" tab on this pull request), as well as in the [Moby contributing guide](https://github.com/moby/moby/blob/v20.10.11/docs/contributing/set-up-git.md).

Steps to do so "roughly" come down to:

1. Set your name and e-mail in git's configuration:

    ```bash
    git config --global user.name "YourFirstName YourLastName"
    git config --global user.email "yourname@example.org"
    ```

    (Make sure to use your _real_ name (**not your GitHub username/handle**) and e-mail)


2. Clone your fork locally
3. Check out the branch associated with this pull request
4. Sign-off and amend the existing commit(s)

    ```bash
    git commit --amend --no-edit --signoff
    ```

    If your pull request contains multiple commits, either squash the commits (if
    needed) or sign-off each individual commit.

5. _Force push_ your branch to GitHub (using the `--force` or [`--force-with-lease`](https://stackoverflow.com/questions/52823692/git-push-force-with-lease-vs-force) flags) to update the pull request.


Sorry for the hassle (I wish GitHub would make this a bit easier to do), and let me know if you need help or more detailed instructions!

**Comment by 0bl** [comment]
Is there a version to be removed in the future?

**Comment by thaJeztah** [comment]
> Is there a version to be removed in the future? Or will it just be deprecated and a warning printed?

I don't expect many users to depend on this behavior, because it's not documented (with millions of users, there always will be _some_ 😂), so I think "one release"  would be enough of a windows for users to be notified, so I would suggest;

- deprecate, and print a warning in the v25.0 release (which is the first upcoming release based on the master/main branch in this repository)
- "remove" (make it an error) in the v26.0 release.

As to the implementation; I had a quick peek at the code, and unfortunately it looks like we don't have direct access to `DockerCli.Err()` in these locations to know where to print to (which would be "better" as it's technically configurable).

I think it would be fine to just hard-code `os.Stderr` for the warning for this one (again, I'm somewhat anticipating that only very few users would depend on this (famous last words 😂)).


As most of these changes are in the same package, perhaps add a small utility would work for that. Something like;


```go
// printCaseInsensitiveWarning prints a warning when an option is used in the
// wrong case.
//
// TODO: remove case-insensitive handling for v26.0.0, and remove this utility.
func printCaseInsensitiveWarning(orig string) {
	if lower := strings.ToLower(orig); lower != orig {
		_, _ = fmt.Fprintf(os.Stderr, "DEPRECATED: the '%s' option is deprecated and will be removed in the next release; use '%s' instead\n", orig, lower)
	}
}
```


Which could be used something like this;

```go
// TODO(thaJeztah): these options should not be case-insensitive.
switch strings.ToLower(key) {
case "valid":
	// do valid stuff
case "also valid":
	// do valid stuff
default:
	return fmt.Errorf("invalid foobar option: %s", key)
}
printCaseInsensitiveWarning(key)
```

**Comment by thaJeztah** [comment]
> I think it would be fine to just hard-code `os.Stderr` for the warning for this one (again, I'm somewhat anticipating that only very few users would depend on this (famous last words 😂)).


I should add that that's my $0.02c - it's other maintainers disagree (and maybe they consider this too much of an edge-case that just announcing it deprecated in the docs is enough, and _printing_ a warning is not needed), but we can discuss that during code review 👍

**Pull request closed without merging**
