### PR TITLE
Add docker-compose schema v3.9

### PR DESCRIPTION
**Pull request by thaJeztah**
This is currently just a copy of the v3.8 schema, in preparation of new features to be added in the new schema.

**- Description for the changelog**

```markdown
* Add support for docker-compose schema v3.9
```

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@ulyssessouza @silvin-lubecki PTAL

**Comment by thaJeztah** [comment]
oh; @silvin-lubecki is on PTO; @vdemeester LGTY? 🤗

**Comment by linuxdep** [comment]
Where can I find a listing of all valid values for v3.8? I have problems with the definition of macvlan. 
It annotates parameters, but I can't find comprehensive documentation on which pairs of values are valid. 
ERROR: compose.cli.main.exit_with_metrics: The Compose file './docker-compose.yml' is invalid because:
networks.macvlan120.ipam.config value 'ip-range' does not match any of the regexes:
my config
networks:
  macvlan120:
    driver: macvlan
    driver_opts:
      parent: eth0
    ipam:
      config:
        - subnet: 192.168.123.0/24
          gateway: 192.168.123.1
          ip-range: 192.168.123.120/29

**Comment by ulgens** [comment]
> This is currently just a copy of the v3.8 schema, in preparation of new features to be added in the new schema.

Why? I know it's been years but it still looks weird to add fake support for a schema version which doesn't exist. Can someone provide a link to docs for 3.9?

**Comment by thaJeztah** [comment]
> Why? I know it's been years but it still looks weird to add fake support for a schema version which doesn't exist. 

It's slightly confusing, but this repository was used as a the canonical definition for the 3.x compose schema (which was designed for use with `docker stack`). The docker compose repository maintained a copy of the definition, and was used to provide documentation for the schemas it supported. 

Unfortunately, the compose _spec_ was created using the copy of the schema in the docker/compose repository as starting point (which was slightly behind this repository), which is why some options were not included in the initial implementation of the compose spec (e.g. https://github.com/compose-spec/compose-spec/pull/214)

**Pull request merged**
