### PR TITLE
cli/command: fix GoDoc referencing wrong const

### PR DESCRIPTION
**Pull request by thaJeztah**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@neersighted ptal 🤗

**Review by neersighted — APPROVED** [review]

**Review by laurazard — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
hmf... gopkg.in is down (again). was hoping it would resolve itself after some time, but it lasts for a while now;

```
#14 245.9 	gopkg.in/yaml.v2@v2.4.0: unrecognized import path "gopkg.in/yaml.v2": reading https://gopkg.in/yaml.v2?go-get=1: 502 Bad Gateway
#14 245.9 	server response: Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: write tcp 10.131.9.188:60820->140.82.121.3:443: write: broken pipe
```

**Comment by thaJeztah** [comment]
Yup, it's not just CI;

```bash
curl 'https://gopkg.in/yaml.v2?go-get=1'
Cannot obtain refs from GitHub: cannot talk to GitHub: Get https://github.com/go-yaml/yaml.git/info/refs?service=git-upload-pack: write tcp 10.131.9.188:60820->140.82.121.3:443: write: broken pipe
```

**Comment by thaJeztah** [comment]
I'll bring this one in as the failure is unrelated, and rebasing would mean I also need to re-do the cherry-pick 😂

**Pull request merged**
