### PR TITLE
Update rm.go

### PR DESCRIPTION
**Pull request by smith518**

### CODE REVIEW

**Comment by laurazard** [comment]
Hi @smith518, thanks for the contribution.

While I'd personally like to add some functionality like this to the CLI, I'm not sure we want to implement it at the CLI level (by having the CLI list all the containers, then make 1 call per container to the engine to remove them – I'd prefer we discussed making some changes to the daemon to allow to make a single call to remove multiple containers), but we haven't discussed that afaik.

Thoughts @thaJeztah?

**Comment by thaJeztah** [comment]
Yeah, not sure about this; also because this overlaps with `docker container prune` (although that does, by design, not prune running containers).

I could see these kind of operations being useful for CI situations ("nuke" everything), but also a bit careful of making them _too_ up-front as part of commands, as in non-CI situations, these are pretty destructive. For CI situations, _most_ situations would already have a fair share of scripts and/or makefiles in  place (which could provide this functionality without much effort).

**Comment by laurazard** [comment]
Yeah, right. For the CI situation/anything scripted I think it's straightforward to write something like `docker rm $(docker ps -aq)` too, although it would be nice to have some better alternative to that.

**Comment by thaJeztah** [comment]
Let me close this one for now, as this requires more discussion; there's an existing tracking ticket for this, which also links to other, related discussions;

- https://github.com/docker/cli/issues/5479

**Pull request closed without merging**
