### PR TITLE
bump github.com/xeipuuv/gojsonschema v1.1.0

### PR DESCRIPTION
**Pull request by thaJeztah**
full diff: https://github.com/xeipuuv/gojsonschema/compare/93e72a773fade158921402d6a24c819b48aba29d...f971f3cd73b2899de6923801c147f075263e0c50

also updated https://github.com/xeipuuv/gojsonpointer to current master

https://github.com/xeipuuv/gojsonpointer/compare/4e3ac2762d5f479393488629ee9370b50873b3a6...02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb

(only a gofmt change)

### CODE REVIEW

**Comment by thaJeztah** [comment]
rebased

**Comment by thaJeztah** [comment]
ping @vdemeester ptal 🤗

**Comment by sreeramaraju** [comment]
Hi, is merging these changes to Master still in pipeline?

**Comment by thaJeztah** [comment]
I think so, but I see it needs a minor rebase 😅 - will do so right away

**Comment by thaJeztah** [comment]
Rebased; also updated https://github.com/xeipuuv/gojsonpointer to current master

https://github.com/xeipuuv/gojsonpointer/compare/4e3ac2762d5f479393488629ee9370b50873b3a6...02993c407bfbf5f6dae44c4f4b1cf6a39b5fc5bb

(only a gofmt change)

**Comment by thaJeztah** [comment]
ping @vdemeester @kolyshkin ptal 🤗

**Pull request merged**
