### PR TITLE
Support Custom Secret Targets

### PR DESCRIPTION
**Pull request by aaronlehmann**
CLI counterpart to https://github.com/moby/moby/pull/32571. Just
involves vendoring github.com/docker/docker/opts.

Don't merge until the moby PR is merged.

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Moby PR was merged; please merge this one.

**Comment by aaronlehmann** [comment]
Actually, let me update the vendoring to the actual moby/moby repo first...

**Comment by aaronlehmann** [comment]
Done. PTAL.

**Comment by stevvooe** [comment]
LGTM

**Pull request merged**
