### PR TITLE
[18.09] Bump Go to 1.10.5

### PR DESCRIPTION
**Pull request by thaJeztah**
go1.10.5 (released 2018/11/02) includes fixes to the go command, linker,
runtime and the database/sql package. See the milestone on the issue
tracker for details:

List of changes; https://github.com/golang/go/issues?q=milestone%3AGo1.10.5

### CODE REVIEW

**Comment by thaJeztah** [comment]
Maked this "WIP", because we don't have a cross-compile image for 1.10.5 https://github.com/docker/cli/blob/v18.09.0/dockerfiles/Dockerfile.cross#L1, which is used in CI; https://github.com/docker/cli/blob/v18.09.0/circle.yml#L24-L49

But I'm ok with merging as-is, and doing that in a follow-up 


ping @andrewhsu @seemethere PTAL

**Comment by seemethere** [comment]
We don't really consume the cross-compile image internally so I don't think we lose a lot by not having it in.

**Comment by thaJeztah** [comment]
ok, let me remove "WIP"; I'll open a PR for the cross-compile image, and update it in a follow-up (just so that CI is all running on the same version)

**Comment by andrewhsu** [comment]
@thaJeztah fyi looks like the 1.10.5 image just popped up https://hub.docker.com/r/dockercore/golang-cross/builds/bxtevckwm6kqux6dpovlvjd/

**Comment by thaJeztah** [comment]
@andrewhsu yes, created a branch, opened a quick PR, and tagged it; I'm updating this PR while we speak

**Comment by thaJeztah** [comment]
Updated! 

```
docker pull dockercore/golang-cross:1.10.5
1.10.5: Pulling from dockercore/golang-cross
54f7e8ac135a: Already exists 
d6341e30912f: Already exists 
087a57faf949: Already exists 
5d71636fb824: Already exists 
f368dba6a331: Already exists 
1ea0c245e5c5: Pull complete 
f81588ba3d2a: Pull complete 
6005d14e174d: Pull complete 
de0caa2f20af: Pull complete 
1957697a71f7: Pull complete 
d23396ac06e8: Pull complete 
Digest: sha256:e41607859366a2480445d196a5a502817e5f6ab90e8b5f55db95375fec0c0008
Status: Downloaded newer image for dockercore/golang-cross:1.10.5
```

**Pull request merged**
