### PR TITLE
Update Windows ico

### PR DESCRIPTION
**Pull request by StefanScherer**
fixes https://github.com/docker/cli/issues/956

Signed-off-by: Stefan Scherer <stefan.scherer@docker.com>

**- What I did**

I've replaces the old Docker ico for the Windows exe files with a newer one.

I've also removed the `docker.png` file as I couldn't find any reference where it may be used. Maybe that was only an example of the ico file for people unable to view Windows ico files.

**- How I did it**

Picked it from an internal JIRA task. :-)

**- How to verify it**

Compile Windows `docker.exe` and check it in Windows Explorer and Sysinternals Process Monitor.

**- Description for the changelog**

Updated the Windows icon.

**- A picture of a cute animal (not mandatory but encouraged)**

systray-icon-win-light-frame0

See also https://github.com/moby/moby/pull/40609

### CODE REVIEW

**Comment by thaJeztah** [comment]
The `.png` looks to be still the old logo? 😅

**Comment by thaJeztah** [comment]
oh, never mind; the png is being deleted here, correct?

**Comment by StefanScherer** [comment]
Yes, it's deleted in that commit. GitHub somehow doesn't show that better for such removed binary files.

**Comment by StefanScherer** [comment]
The relevant change is in the `.ico` file which is used here https://github.com/docker/cli/blob/master/scripts/winresources/common.rc
The `.png` seems unused.

**Comment by thaJeztah** [comment]
Ah, interesting. Actually recall looking at that at some point, but wasn't sure if the `.png` would implicitly be used somewhere

**Pull request merged**
