### PR TITLE
Bump docker/docker to cd35e4beee13a7c193e2a89008cd87d38fcd0161

### PR DESCRIPTION
**Pull request by thaJeztah**
Reverts changes in pkg/term related to `OPOST` that pulled in through;
3574e6a674086a6d7fae9adbb17d5f80b2c0a714

And reverted upstream in;
https://github.com/moby/moby/commit/cd35e4beee13a7c193e2a89008cd87d38fcd0161 (https://github.com/moby/moby/pull/33577)

Full diff;
https://github.com/moby/moby/compare/c8141a1fb1ff33b2bfab85a40e5da9a282f36cdc...cd35e4beee13a7c193e2a89008cd87d38fcd0161

ping @crosbymichael @vieux

### CODE REVIEW

**Comment by thaJeztah** [comment]
Added "cherry-pick" label, but we should only cherry-pick the changes from https://github.com/moby/moby/commit/cd35e4beee13a7c193e2a89008cd87d38fcd0161

**Comment by crosbymichael** [comment]
LGTM

**Comment by dnephin** [comment]
I removed `HeaderSize`, and `IsArchive` from `pkg/archive` because they weren't used in moby/moby. I can push a commit to this PR which restores them in `docker/cli`.

**Comment by dnephin** [comment]
I pushed a commit which should fix the tests

**Comment by vieux** [comment]
LGTM

**Pull request merged**
