### PR TITLE
vendor: bump docker/docker, docker/swarmkit, and dependencies

### PR DESCRIPTION
**Pull request by thaJeztah**
see individual commits for details

### CODE REVIEW

**Comment by thaJeztah** [comment]
Looks like go-metrics needs to be updated for changes in prometheus;

```
=== Errors
vendor/github.com/docker/go-metrics/handler.go:12:9: undefined: prometheus.Handler
vendor/github.com/docker/go-metrics/timer.go:39:16: cannot use lt.m.WithLabelValues(labels...) (type prometheus.Observer) as type prometheus.Histogram in field value:
	prometheus.Observer does not implement prometheus.Histogram (missing Collect method)
```

**Comment by thaJeztah** [comment]
Ah! Looks like I mentioned that in https://github.com/docker/cli/pull/2333#discussion_r378401968, but forgot to open a PR for it 😅

**Comment by thaJeztah** [comment]
@silvin-lubecki PTAL

**Review by silvin-lubecki — APPROVED** [review]
Looks good 👍

**Pull request merged**
