### PR TITLE
docs: add missing ID placeholder for docker node ps

### PR DESCRIPTION
**Pull request by thaJeztah**
fixes https://github.com/docker/docker.github.io/issues/6055

### CODE REVIEW

**Comment by thaJeztah** [comment]
Temporary glitch on Docker Hub; I'll force-push in a few minutes to trigger CI again

**Comment by thaJeztah** [comment]
@thebsdbox ptal 🤗

**Comment by thaJeztah** [comment]
author LGTM

**Comment by thebsdbox** [comment]
LGTM (sorry was on holiday 🏂 )

**Pull request merged**
