### PR TITLE
docs: add anchor tags for command-line flags

### PR DESCRIPTION
**Pull request by thaJeztah**
This will generate "details_url" for options, so that the options
table on the pages at docs.docker.com link to the section describing
the option.

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
opened https://github.com/docker/docker.github.io/pull/14478 to test it in the docs repository

**Comment by thaJeztah** [comment]
Alright; this works; it's not _perfect_ yet, as there's many flags that don't have a dedicated section (yet), and there's some flags that are described in combination with other flags (e.g. grouping `--add-host` and `--rm-host` in the same paragraph), but it's  a start.


This page, for example, now has anchors for various flags; https://deploy-preview-14478--docsdocker.netlify.app/engine/reference/commandline/build/#options

We should also have a look at making the links more _visible_ in the Options table, as currently it's not clear which ones are clickable, and which ones are not.

**Comment by thaJeztah** [comment]
@silvin-lubecki @crazy-max PTAL (you may want to review per-commit; first couple of commits were some formatting fixes)

**Review by silvin-lubecki — APPROVED** [review]
Looks good 👀

**Comment by thaJeztah** [comment]
alright; let's get this one in (I think there's a couple of headers I missed, but it's a start)

**Pull request merged**
