### PR TITLE
Update Notary vendor to 0.6.0 release

### PR DESCRIPTION
**Pull request by justincormack**
We were on a slightly earlier random commit.

We should try to stay on releases where possible...

Signed-off-by: Justin Cormack <justin.cormack@docker.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Full diff: https://github.com/theupdateframework/notary/compare/05985dc5d1c71ee6c387e9cd276a00b9d424af53...v0.6.0

Changes included:

- https://github.com/theupdateframework/notary/pull/1260 return errors for invalid key pem blocks
- https://github.com/theupdateframework/notary/pull/1263 remove warning when checking if delegation certs have expired
- https://github.com/theupdateframework/notary/pull/1286 Add some filepaths on Fedora where libykcs11 may be found



@justincormack can you check if we need to bump Notary's dependencies to match?

- https://github.com/docker/go-connections/compare/7beb39f0b969b075d1325fecb092faf27fd357b6...7395e3f8aa162843a74ed6d48e79627d9792ac55
  - https://github.com/docker/go-connections/pull/49 Remove TLS_RSA ciphers from the default accepted cipher suite
  - https://github.com/docker/go-connections/pull/50 Remove server support for TLS 1.0 and 1.1
- https://github.com/miekg/pkcs11/compare/df8ae6ca730422dba20c768ff38ef7d79077a59f...5f6e0d0dad6f472df908c8e968a98ef00c9224bb
  - *21 commits behind*

Already ahead:

- https://github.com/golang/sys/compare/37707fdb30a5b38865cfb95e5aab41707daec7fd...314a259e304ff91bd6985da2a7149bbf91237993
  - already 95 commits ahead
- https://github.com/opencontainers/go-digest/compare/21dfd564fd89c944783d00d069f33e3e7123c448...a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb
  - already 6 commits ahead
- https://github.com/spf13/cobra/compare/34ceca591bcf34a17a8b7bad5b3ce5f9c165bee5...7b2c5ac9fc04fc5efafb60700713d4fa609b777b
  - irrelevant, and already 9 commits ahead
- https://github.com/spf13/pflag/compare/97afa5e7ca8a08a383cb259e06636b5e2cc7897f...e57e3eeb33f795204c1ca35f56c44f83227c6e66
  - irrelevant, and already 9 commits ahead

**Comment by thaJeztah** [comment]
Also see e2e tests pin to notary 0.4.2 3 (likely not relevant); https://github.com/docker/cli/blob/b70f9296dd2585ca655a30d3d8e3dce812a7fc7f/e2e/compose-env.yaml#L1

**Comment by justincormack** [comment]
Added the pkcs11 dep update. go-connections only affects servers so not really important here, we should probably update when we update docker.

**Comment by justincormack** [comment]
The library images havent been updated yet...

**Pull request merged**
