### PR TITLE
Add a Close method on DockerCli

### PR DESCRIPTION
**Pull request by lgarithm**
**- What I did**
Added a Close method on DockerCli.

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by dnephin** [comment]
Since this is unused by the cli I don't really like adding this. You can already call close with `DockerCli.Client().Client()`

**Comment by lgarithm** [comment]
DockerCli.Client() returns an interface client.APIClient, which doesn't have a Close method.

* https://github.com/docker/cli/blob/master/cli/command/cli.go#L66
* https://github.com/docker/cli/blob/master/vendor/github.com/docker/docker/client/interface_stable.go#L4

**Comment by dnephin** [comment]
That will be fixed in https://github.com/moby/moby/pull/34899

**Comment by lgarithm** [comment]
That would be nice!
When will it be merged into docker/cli?

**Pull request closed without merging**
