### PR TITLE
vndr docker/docker to ea220e7 to bring in fix for arm

### PR DESCRIPTION
**Pull request by andrewhsu**
**- What I did**

Primarily to bring in fix for:
* moby/moby/pull/34021 Clear Architecture field in platform constraint for arm architectures

Although there are several other changes that are in this update:
https://github.com/moby/moby/compare/184cea5...ea220e7

I also had to update vndr for golang.org/x/sys to bring in changes required by the moby/moby re-vndr: https://github.com/golang/sys/compare/7397344...07c1829

**- How I did it**

```
$ make -f docker.Makefile shell
$ vi vendor.conf
$ vndr github.com/docker/docker
$ vndr golang.org/x/sys
```

**- How to verify it**

run vndr again and see nothing changes

**- Description for the changelog**

* update vndr of docker/docker and golang.org/x/sys to bring in fixes for arm

**- A picture of a cute animal (not mandatory but encouraged)**

🐸

### CODE REVIEW

**Comment by andrewhsu** [comment]
cc @nishanttotla @tiborvass @dnephin

**Comment by nishanttotla** [comment]
LGTM (the arm commit is there and looks good. Can't comment on the rest of the commit tree also being vendored in)

**Comment by dnephin** [comment]
Looks like `golang.org/x/sys` needs to be updated to `07c182904dbd53199946ba614a412c61d3c548f5`

**Comment by dnephin** [comment]
Please also remove `github.com/docker/libtrust` from `vendor.conf`, it looks like it is no longer needed. There should be a warning come from `vndr` about that.

**Comment by andrewhsu** [comment]
@dnephin looks like build got cancelled because of circleci something something. is there a way to poke it again?

**Comment by andrewhsu** [comment]
`git commit --amend` is my friend now

**Comment by vieux** [comment]
LGTM

**Comment by StefanScherer** [comment]
@andrewhsu Just got a RPi3 with internet connection and installed docker-ce_17.09.0~ce~rc3-0~raspbian_armhf.deb, created a swarm and I'm able to create swarm services 👍

**Pull request merged**
