### PR TITLE
revendor logrus and x/crypto

### PR DESCRIPTION
**Pull request by thaJeztah**
I originally had these in https://github.com/docker/cli/pull/570, but didn't know if the x/crypto changes would affect the recently added `docker trust` commands (https://github.com/docker/cli/pull/472), so decided to keep it separate.

These dependencies were bumped upstream in https://github.com/moby/moby/pull/34332 to address some issues with PowerPC64le

ping @riyazdf @clnperez @tophj-ibm PTAL

### CODE REVIEW

**Comment by clnperez** [comment]
thanks @thaJeztah for these bumps. i see no issues with this.

**Comment by riyazdf** [comment]
@tophj-ibm: that's unexpected - is it the same for `DOCKER_CONTENT_TRUST=1 docker push`?  And `notary` from master?  We can follow up on community-slack too for more details, I'll give this a spin

**Comment by thaJeztah** [comment]
thanks for reviewing!

**Comment by vieux** [comment]
LGTM

**Pull request merged**
