### PR TITLE
compose: add build.extra_hosts to v3.9 schema

### PR DESCRIPTION
**Pull request by thaJeztah**
This is not currently used by the CLI, but can be used by docker compose to bring parity on this feature with the compose v2.4 schema.

relates to https://github.com/docker/compose/issues/7323

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@silvin-lubecki @ndeloof PTAL

**Comment by ndeloof** [comment]
Compose canonical schema should be https://github.com/compose-spec/compose-spec/blob/master/schema/config_schema_v3.9.json and such change should only take place after a public proposal to the compose-spec community

**Comment by thaJeztah** [comment]
@ndeloof what I understood is that the current 3.9 spec was used as the transition to make compose-spec the canonical place because it was already worked on for the upcoming 20.03 release; if compose-spec is the canonical place, should this repository vendor the spec from that location? (also this means we have a release blocker for 20.03, pending https://github.com/docker/cli/pull/2503

**Comment by agners** [comment]
@thaJeztah @ndeloof this is utterly frustrating for outside contributors. I created a merge request months ago adding `device_cgroup_rules` (see https://github.com/docker/cli/pull/2206). However it got ignored/sidelined. With the compose-spec comming along, I did all my home work and helped making it part of the upcoming spec https://github.com/compose-spec/compose-spec/pull/63. 

And now, within 4 days other properties make it in directly into CLI's compose spec? So now compose-spec essentially forked??

**Comment by ndeloof** [comment]
https://github.com/compose-spec/compose-go is the exact same codebase as docker/cli for compose file loading and mdel (this is a git extract, including history). CLI _should_ be updated to adopt compose-go and throw avoid code to diverge like this. This is more a question of finding the right timing vs CLI release schedule.

**Comment by agners** [comment]
@ndeloof @thaJeztah since we won't adopt compose-go in time for 20.03, could we then not just merge #2206? I would mean less divergence from compose-spec...

**Comment by ndeloof** [comment]
compose-spec is going to re-introduce all v2 attributes in the schema by approval of https://github.com/compose-spec/compose-spec/issues/12
so #2206 still make sense, this won't introduce a divergence.

**Comment by burka** [comment]
For anyone searching like me: It's solved in Version 3.9 https://github.com/docker/cli/pull/2517 - you can add `extra_hosts:` in `build:` now.

**Pull request merged**
