### PR TITLE
CLI: Add support for using Configs as CredentialSpecs in services

### PR DESCRIPTION
**Pull request by thaJeztah**
depends on ~https://github.com/moby/moby/pull/38672~ https://github.com/moby/moby/pull/38632 (using a temporary vendoring), ~and built on top of https://github.com/docker/cli/pull/1655 (which isn't merged yet)~

- Improve validation of credential_spec in compose schema (I'll split that to a separate PR as well)
- Add compose schema 3.8
- Add `config` as option in credential_spec

### CODE REVIEW

**Comment by thaJeztah** [comment]
ping @dperny @vdemeester @tiborvass PTAL

**Comment by thaJeztah** [comment]
split the compose-file validation for older versions to https://github.com/docker/cli/pull/1657

**Comment by simonferquel** [comment]
Should'nt credentials be stored as Secret objects more than Configs ?

**Comment by thaJeztah** [comment]
IIUC, the content of the credentials-spec doesn't contain sensitive data (implementation-wise, it wouldn't make a big difference currently, as both are encrypted and use the same storage)

**Comment by vdemeester** [comment]
@thaJeztah needs a PR and some updates ?

**Comment by thaJeztah** [comment]
Rebased on top of https://github.com/docker/cli/pull/1700, but there's still discussion about the current implementation in moby, so let's hold off merging this until that's in https://github.com/moby/moby/pull/38777#discussion_r259333961


/cc @ddebroy @dperny @wk8

**Comment by thaJeztah** [comment]
hm..

```
=== FAIL: cli/compose/loader TestMarshallConfig (0.03s)
    types_test.go:26: assertion failed: error is not nil: max_replicas_per_node Additional property max_replicas_per_node is not allowed

=== FAIL: cli/compose/loader TestJSONMarshallConfig (0.03s)
    types_test.go:42: assertion failed: error is not nil: max_replicas_per_node Additional property max_replicas_per_node is not allowed
```

**Comment by dperny** [comment]
Final implementation for CredentialSpecs through swarm configs is done, so this can move forward. 

The implementation of this feature requires two things: the Config needs to be in the ConfigReferences for the service, and the Config used for the CredentialSpec needs to be specified by ID, not by name.

Because ConfigReferences already must include the ConfigID, the logic we use to fill in that field should be used in turn to fill in the CredentialSpec field in the Service object appropriately. My vision of the CLI is to have this flag:

```
--credential-spec config://my-config-name
```

turn into these objects:

```go
// assume the existence of some function `resolveConfigID(string) string`
// which takes a config name and returns its ID
credentialSpec := &swarm.CredentialSpec{
    Config: resolveConfigID(strings.TrimPrefix(value, "config://")),
}
```

```go
func addCredentialSpecConfig(spec *swarm.ServiceSpec, c *swarm.Config) {
    spec.TaskTemplate.ContainerSpec.Configs = append(spec.TaskTemplate.ContainerSpec.Configs,
        &swarm.ConfigReference{
            Runtime: &swarm.ConfigReferenceRuntimeTarget{},
            ConfigID: c.ID,
            ConfigName: c.Name,
        },
    )
}
```

**Comment by dperny** [comment]
I'm going to pull down @thaJeztah's branch and make these changes myself.

**Pull request closed without merging**
