### PR TITLE
[20.10 backport] Add completion for docker-compose plugin

### PR DESCRIPTION
**Pull request by thaJeztah**
- backport of https://github.com/docker/cli/pull/3158
- backport of https://github.com/docker/cli/pull/3392
- relates to https://github.com/docker/compose-cli/pull/1773
- relates to https://github.com/docker/cli/issues/1257

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
Perhaps we should have something similar for zsh completion 🤔

**Review by vvoland — APPROVED** [review]

**Comment by thaJeztah** [comment]
Ci failing on something that looks like a race condition in `TestRemoveForce` - let me try backporting https://github.com/docker/cli/pull/3520

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/3753

**Review by albers — APPROVED** [review]

**Comment by thaJeztah** [comment]
Thx for review! Let me get this one in

**Pull request merged**
