### PR TITLE
vendor: containerd v1.6.2, buildkit v0.10.0

### PR DESCRIPTION
**Pull request by thaJeztah**
### vendor: google.golang.org/grpc v1.44.0

full diff: https://github.com/grpc/grpc-go/compare/v1.38.0...v1.44.0

### vendor: github.com/containerd/containerd v1.6.2

full diff: https://github.com/containerd/containerd/compare/v1.5.10...v1.6.2

### vendor: github.com/prometheus/procfs v0.7.3

un-pinning the dependency to let go modules resolve the version to use.

full diff: https://github.com/prometheus/procfs/compare/v0.0.11...v0.7.3

### vendor: github.com/prometheus/client_golang v1.11.0

un-pin the dependency to let go modules resolve the version

full diff: https://github.com/prometheus/client_golang/compare/v1.6.0...v1.11.0

### vendor: github.com/moby/buildkit v0.10.0

full diff: https://github.com/moby/buildkit/compare/9f254e18360a...v0.10.0

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@rumpl @crazy-max PTAL

**Comment by crazy-max** [comment]
I wonder if the buildkit dependency is still something required here. It looks like we depend on it for only two small pkgs that could be directly integrated here:

https://github.com/docker/cli/blob/6745f62a0b8c5c2a00306723da5fb835a7087ebd/cmd/docker/docker.go#L18

https://github.com/docker/cli/blob/6745f62a0b8c5c2a00306723da5fb835a7087ebd/cmd/docker/docker.go#L198-L201

___

https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/command/image/build/dockerignore.go#L8

https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/cli/command/image/build/dockerignore.go#L25

The dockerignore one needs more thoughts though: https://github.com/moby/buildkit/issues/2734#issuecomment-1071769146

**Comment by thaJeztah** [comment]
Yes, I was also looking at some bits for the dockerignore, and for context I want to look at getting rid of `pkg/urlutil`, which looks like it made its way into other areas where it shouldn't be used (and I think there's equivalents to that in buildkit); https://github.com/moby/moby/tree/babb0c14fd1281b309de46c3481a5bea88b8031d/pkg/urlutil

**Comment by thaJeztah** [comment]
@crazy-max those things ok to do in a follow-up (if possible?)? Looks like we may not be able to resolve them immediately (in this repository), or at least only _partial_

**Review by crazy-max — APPROVED** [review]
Yes let's think about that in a follow-up

**Comment by thaJeztah** [comment]
Thx!

**Pull request merged**
