### PR TITLE
Add albers to maintainers

### PR DESCRIPTION
**Pull request by dnephin**
He is primary maintainer of the bash completion scripts.

### CODE REVIEW

**Comment by thaJeztah** [comment]
LGTM :+1:

**Comment by thaJeztah** [comment]
Welcome (again) @albers 🎉

**Comment by albers** [comment]
Back on the road again - thanks!

**Comment by albers** [comment]
@thaJeztah did you enjoy Iceland?

**Comment by thaJeztah** [comment]
Yes, I did! Now dealing with a huge pile of notifications, haha :smile:

**Comment by albers** [comment]
@thaJeztah I still got no commit access. Can you please check the permissions?

**Comment by thaJeztah** [comment]
Oh, ha, don't think I'm an admin for this repository: @dnephin could you check?

**Comment by dnephin** [comment]
cc @vieux (I'm not either)

**Comment by vieux** [comment]
@thaJeztah @dnephin @albers done, welcome back @albers 🎉

**Pull request merged**
