### PR TITLE
Add Sam Thibault (sam-thibault) as curator

### PR DESCRIPTION
**Pull request by thaJeztah**
Sam is on my team, and we started to do weekly triage sessions to clean up the backlog. Adding him, so that he can help with doing triage without my assistance :)

**- A picture of a cute animal (not mandatory but encouraged)**

otter

### CODE REVIEW

**Review by vvoland — APPROVED** [review]

**Review by rumpl — APPROVED** [review]
👍

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Review by sam-thibault — APPROVED** [review]
thanks @thaJeztah

**Comment by thaJeztah** [comment]
Whoop! let me merge this one 👍

**Pull request merged**
