### PR TITLE
vendor: github.com/docker/docker cfdca8dc1d4c (v25.0.0-dev)

### PR DESCRIPTION
**Pull request by thaJeztah**
- relates to https://github.com/moby/moby/pull/46481

full diff: https://github.com/docker/docker/compare/v25.0.0-beta.1...cfdca8dc1d4c84ee235f395a011ca62315c957a7

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
No significant changes, so I'll keep this in draft for now.

**Comment by thaJeztah** [comment]
Oh! Actually relevant changes. I actually wanted to update the vendor because of those, but then thought they were not part of vendor, but they are;


```
60.33 cli/command/service/update.go:1298:18: SA1019: spec.Networks is deprecated: This field is deprecated since v1.44. The Networks field in TaskSpec should be used instead. (staticcheck)
60.33 		specNetworks = spec.Networks
60.33 		               ^
60.33 cli/command/service/update.go:1300:2: SA1019: spec.Networks is deprecated: This field is deprecated since v1.44. The Networks field in TaskSpec should be used instead. (staticcheck)
60.33 	spec.Networks = nil
60.33 	^
60.33 cli/compose/convert/service.go:177:3: SA1019: serviceSpec.Networks is deprecated: This field is deprecated since v1.44. The Networks field in TaskSpec should be used instead. (staticcheck)
60.33 		serviceSpec.Networks = networks
60.33 		^
```

**Comment by thaJeztah** [comment]
> ⚠️ if we update, we probably may have to do so based on API version, or otherwise make sure that the apiClient itself takes care of that.

Chatted with @akerouanton and conversion is already there, so we only needed `nolint` comments 👍

**Review by akerouanton — APPROVED** [review]
LGTM!

**Pull request merged**
