### PR TITLE
commandconn: set SysProcAttr.Setsid (Fix DOCKER_HOST=ssh://host-behind-bastion)

### LINKED ISSUE #1707: [ssh connhelper] /dev/stdin EAGAIN
**Description**

`DOCKER_HOST=ssh://...` does not work with `docker run -i` on certain conditions, due to `Error sendStdin: read /dev/stdin: resource temporarily unavailable`.

**Steps to reproduce the issue:**
1. ` DOCKER_HOST=ssh://suda-debian docker run -it --rm alpine`

**Describe the results you received:**
Shell prompt does not appear

**Describe the results you expected:**
Shell prompt appears

**Additional information you deem important (e.g. issue happens only occasionally):**

Debug logs:
```
$ DOCKER_HOST=ssh://suda-debian docker --debug run -it --rm alpine
DEBU[0000] connhelper: starting ssh with [suda-debian -- docker system dial-stdio]
DEBU[0001] connhelper: starting ssh with [suda-debian -- docker system dial-stdio]
DEBU[0003] connhelper: starting ssh with [suda-debian -- docker system dial-stdio]
                                                                                   DEBU[0003] [hijack] End of stdin
DEBU[0003] Error sendStdin: read /dev/stdin: resource temporarily unavailable
DEBU[0003] [hijack] End of stdout
```

* Not reproducible with macOS client.
* Not reproducible with a daemon running in a local LXC container. So the issue is likely to be  related to network latency.
* Not reproducible when stdin is not tty, i.e. `echo foo | DOCKER_HOST=ssh://suda-debian docker --debug run -i --rm alpine cat` works
* Client: Ubuntu 18.04.2, kernel `4.15.0-45-generic #48-Ubuntu`, bash, tmux

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           18.09.3
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        774a1f4
 Built:             Thu Feb 28 06:32:01 2019
 OS/Arch:           linux/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          18.09.3
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       774a1f4
  Built:            Thu Feb 28 05:59:55 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Output of `docker info`:**

```
Containers: 16
 Running: 16
 Paused: 0
 Stopped: 0
Images: 9
Server Version: 18.09.3
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e
runc version: 6635b4f0c6af3810594d2770f662f34ddc15b40d
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.0-8-amd64
Operating System: Debian GNU/Linux 9 (stretch)
OSType: linux
Architecture: x86_64
CPUs: 32
Total Memory: 118GiB
Name: suda-debian
ID: NTDN:QBDF:Y6PR:QUUL:QRLD:AYSL:27JV:5VJG:QXL5:T5CS:5S3A:7BCT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Username: akihirosuda
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine

WARNING: No swap limit support
```

### PR DESCRIPTION
**Pull request by AkihiroSuda**
Signed-off-by: Akihiro Suda <suda.akihiro@lab.ntt.co.jp>

**- What I did**

Fixed SSH connection helper with `ProxyCommand` config.

Fix #1707 

**- How I did it**

Set `SysProcAttr.Setsid`

**- How to verify it**

```console
$ cat ~/.ssh/config
Host foo 
  Hostname foo
  ProxyCommand ssh -W %h:%p bastion
$ DOCKER_HOST=ssh://foo docker run -it --rm alpine
/ #
```

**- Description for the changelog**

Fixed SSH connection helper with `ProxyCommand` config.

**- A picture of a cute animal (not mandatory but encouraged)**
https://twitter.com/aveirjapan/status/1101598199280623616

### CODE REVIEW

**Comment by thaJeztah** [comment]
@tonistiigi @ijc PTAL

**Comment by ijc** [comment]
> Setting `Setsid` is needed for SSH connection helper with `ProxyCommand` config.

Please can you explain why this is the case, using the `Host foo` runes you gave in the commit message works for me and I don't immediately see the link between `setsid` and `ProxyCommand` nor `stdin` being non-blocking, I suspect there is something more subtle at work here which is worth documenting (ideally in the commit message).

**Comment by AkihiroSuda** [comment]
It is for detaching TTY, but tbh I'm not sure how the helper process is making stdin non-blocking..

**Comment by ijc** [comment]
Doesn't Go make any filedescriptor which gets into its i/o scheduler non-blocking? Not clear how stdin has gotten into a path like that in this case though.

**Comment by AkihiroSuda** [comment]
I straced docker and ssh but could not figure out how stdin is made non-blocking.

@cpuguy83 @tonistiigi PTAL?

**Comment by tonistiigi** [comment]
SGTM

**Comment by AkihiroSuda** [comment]
any chance to get this merged?

**Comment by AkihiroSuda** [comment]
@cpuguy83 @ijc @thaJeztah PTAL?

**Pull request merged**
