### PR TITLE
fixes #1459 handle archive with paxHeader or not when docker build

### LINKED ISSUE #1459: Need to handle archive with paxHeader or not when docker build
**Description**
For https://github.com/moby/moby/issues/38059
We need to handle archive with paxHeader or not when docker build
Because git archive has paxHeader:
```
pax_global_header

  "presets": ["es2015"]
}

branch = True

source = measurements

[report]
exclude_lines = 
    # pragma: no cover
```
But regular tar file doesn't have it.

**Describe the results you received:**
See https://github.com/moby/moby/issues/38059

**Describe the results you expected:**
See https://github.com/moby/moby/issues/38059

### PR DESCRIPTION
**Pull request by lifubang**
Signed-off-by: Lifubang <lifubang@acmcoder.com>

**- What I did**
If tar file with paxHeader, func IsArchive can't check it correctly.
See https://github.com/moby/moby/issues/38059 #1459
Tar file with paxHeader:
```
pax_global_header

  "presets": ["es2015"]
}

branch = True

source = measurements

[report]
exclude_lines = 
    # pragma: no cover
```

**- How I did it**
Expand archiveHeaderSize and recheck it.

**- How to verify it**
After fix:
```
root@dockerdemo:~/api# git archive --format=tar 210e8603aea57e03e3fc6066d5967c2bf53879a9 | ~/gocode/src/github.com/docker/cli/build/docker build -t test -
IsArchive Error: unexpected EOF
IsArchive Error: <nil>
IsArchive: True
 
Sending build context to Docker daemon   8.52MB
Step 1/14 : FROM python:3.5.2-slim
^C
root@dockerdemo:~/api#
```

**- Description for the changelog**
Support git archive and other tar file with paxHeader

**- A picture of a cute animal**
i67 op146 pnf9u5zhlp6zk

### CODE REVIEW

**Comment by lifubang** [comment]
@silvin-lubecki Thanks. Finished. PTAL

**Comment by kolyshkin** [comment]
Easier fix: https://github.com/docker/cli/pull/1770

**Comment by lifubang** [comment]
@kolyshkin Thank you for your view.
I don't know whether we need to consider the file size which is small than 1024bytes or not?
If not, this PR can be closed!

**Comment by kolyshkin** [comment]
@lifubang thanks for your input. I just spent some time trying to create a tar archive shorter than 1K (and it's possible if it is gzipped). The thing is, it can even be less than 512 bytes -- I have 85 bytes tar.gz -- but it's not important because the code handles it:

```go
	magic, err := buf.Peek(archiveHeaderSize * 2)
	if err != nil && err != io.EOF {
￼...
```

i.e. short read is ignored. I have also run your test with this 85 bytes archive, it works fine.

**Pull request closed without merging**
