### PR TITLE
Support for rollback config in compose 3.7

### PR DESCRIPTION
**Pull request by alshabib**
Fixes moby/moby#32585

**- What I did**

Built off https://github.com/docker/cli/pull/360 to provide support for rollback config in compose 3.4. ie.

```
  deploy:
      replicas: 1
      rollback_config:
        parallelism: 1
```

**- How I did it**

Added the key to the schema, regenerated the schema and tied it to existing UpdateConfig type.

**- How to verify it**

```
docker stack deploy -c docker-compose.yml yay
```

with the following stack:

```
version: '3.7'

services:
  busy:
    image: busybox
    deploy:
      replicas: 1
      rollback_config:
        parallelism: 1
    ports:
      - 80:80
```

**- Description for the changelog**
This pull request adds support for rollback configurations to be specified in the YAML stack file. Given that it is build off the aforementioned pull request, it supports also rollback_config.order.

**- A picture of a cute animal (not mandatory but encouraged)**

dog

### CODE REVIEW

**Comment by alshabib** [comment]
anything blocking this?

**Comment by vdemeester** [comment]
@vieux @dnephin has 17.08 freeze started or shouldn't this be for compose 3.5 ?

**Comment by sirlatrom** [comment]
@alshabib Any chance you could update this PR so it might make it into spec version 3.5?

**Comment by alshabib** [comment]
Sure. Just pushed an update.

**Comment by dnephin** [comment]
This needs to be moved to version 3.5 schema now, otherwise LGTM

**Comment by Vadus** [comment]
is this in 3.5 already ? 

and does the `rollback_config` work also on `<service> -> deploy: -> update_config: -> failure_action: continue` ?

**Comment by vdemeester** [comment]
@thaJeztah rebased, fixed conflicts and update to be on composefile 3.7 :angel:

**Pull request merged**
