### PR TITLE
Dockerfile: update xx to 1.1

### PR DESCRIPTION
**Pull request by thaJeztah**
splitting up https://github.com/docker/cli/pull/3383 (where we're debugging some issues with cross compiles); moving this to a separate PR so that we can test/merge some changes in isolation.

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
FTR, so the `osusergo` issue is indeed already present in current builds (so not new in https://github.com/docker/cli/pull/3383);

```
#37 399.9 /usr/bin/s390x-linux-gnu-ld: /tmp/go-link-800461440/000018.o: in function `mygetgrouplist':
1734
#37 399.9 /usr/local/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
```

**Review by crazy-max — APPROVED** [review]

**Comment by thaJeztah** [comment]
thx!

**Comment by thaJeztah** [comment]
We should fix this; or does `xx` also have a `apt-get` ? `apt` meant for "humans", and not meant for scripting (see the warning);

```
#54 [linux/amd64 build-buster 1/1] RUN xx-apt install --no-install-recommends -y libc6-dev libgcc-8-dev
#54 0.706 Hit:1 http://security.debian.org/debian-security buster/updates InRelease
#54 0.707 Hit:2 http://deb.debian.org/debian buster InRelease
#54 0.708 Hit:3 http://deb.debian.org/debian buster-updates InRelease
#54 2.149 Reading package lists...
#54 4.917 + apt  install --no-install-recommends -y libc6-dev libgcc-8-dev
#54 4.934 
#54 4.934 WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
#54 4.934 
```

**Comment by crazy-max** [comment]
Yes xx has `apt-get`: https://github.com/tonistiigi/xx/pull/40

**Comment by thaJeztah** [comment]
Yup, just found it; https://github.com/tonistiigi/xx/blob/v1.1.0/base/xx-apt#L58 😂

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/3491

**Pull request merged**
