### PR TITLE
Add gcc and musl-dev to dev Dockerfile

### PR DESCRIPTION
**Pull request by seemethere**
Needed to be able to do `make -f docker.Makefile binary` on multiple
architectures.

Signed-off-by: Eli Uriegas <eli.uriegas@docker.com>

**- What I did**
Fixed `make -f docker.Makefile binary` on `aarch64`, would fail before with:

```
Step 4/11 : RUN     go get -d github.com/LK4D4/vndr &&         cd /go/src/github.com/LK4D4/vndr &&         git checkout -q "$VNDR_SHA" &&         go build -v -o /usr/bin/vndr . &&         rm -rf /go/src/* /go/pkg/* /go/bin/*
 ---> Running in bffec54b704f
github.com/LK4D4/vndr/godl/singleflight
github.com/LK4D4/vndr/build
github.com/LK4D4/vndr/godl
github.com/LK4D4/vndr
# github.com/LK4D4/vndr
/usr/local/go/pkg/tool/linux_arm64/link: running gcc failed: exec: "gcc": executable file not found in $PATH

The command '/bin/sh -c go get -d github.com/LK4D4/vndr &&         cd /go/src/github.com/LK4D4/vndr &&         git checkout -q "$VNDR_SHA" &&         go build -v -o /usr/bin/vndr . &&         rm -rf /go/src/* /go/pkg/* /go/bin/*' returned a non-zero code: 2
docker.Makefile:18: recipe for target 'build_docker_image' failed
make: *** [build_docker_image] Error 2
```

**- How I did it**

* Added `gcc` and `musl-dev` to the Dockerfile.dev

**- How to verify it**
* Running `make -f docker.Makefile binary` on `aarch64` 

**- Description for the changelog**

```
* Added `gcc` and `musl-dev` to the `Dockerfile.dev`
```

**- A picture of a cute animal (not mandatory but encouraged)**
darth bird

### CODE REVIEW

**Comment by dnephin** [comment]
Can we just use `Dockerfile.cross ` dockerfile instead?

If not, can we go with this solution: https://github.com/docker/cli/issues/183#issuecomment-307947368

**Comment by seemethere** [comment]
The base is multi arch already. There's just 2 extra dependencies to add for compiling on different architectures.

**Comment by arm64b** [comment]
IMO we need this RP to build a docker image natively on AArch64 while not use a `cross` solution.  /cc @dnephin

**Comment by dnephin** [comment]
See #816 for another solution

**Pull request closed without merging**
