### PR TITLE
Add `docker engine` commands only on Linux…

### PR DESCRIPTION
**Pull request by vdemeester**
… this is, for now, the only platform that is supported

cc @jeanlaurent @gtardif @andrewhsu @eli @seemethere @chris-crone 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by vdemeester** [comment]
```
13:01:15 === RUN   TestDockerEngineOnContainerdAltRootConfig
13:01:23 --- FAIL: TestDockerEngineOnContainerdAltRootConfig (7.79s)
13:01:23 	altroot_test.go:20: First engine init
13:01:23 	altroot_test.go:33: perform update
13:01:23 	altroot_test.go:37: assertion failed: 
13:01:23 		Command:  docker engine update --version 18.09.0-dev
13:01:23 		ExitCode: 1
13:01:23 		Error:    exit status 1
13:01:23 		Stdout:   
13:01:23 		Stderr:   failed to update to new image: mount callback failed on /tmp/containerd-mount769954539: rpc error: code = NotFound desc = content digest sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1: not found
13:01:23 		
13:01:23 		
13:01:23 		Failures:
13:01:23 		ExitCode was 1 expected 0
13:01:23 		Expected stdout to contain "Success!  The docker engine is now running."
13:01:23 		Expected no error
13:01:23 	utils.go:13: doing engine cleanup
```

Flakyness ? :thinking:

**Comment by seemethere** [comment]
These commands don't really make sense on non-linux OS's so it'd be a good idea to not add them in the first place.

**Comment by ijc** [comment]
Is there a point/benefit to registering the `docker engine` command itself when not registering the subcommands?

**Comment by seemethere** [comment]
@thaJeztah I believe @vdemeester said that the annotation doesn't cover the case on mac since the daemon is still ostype linux (running in a linuxkit VM)

**Comment by vdemeester** [comment]
So discussed a bit offline with @thaJeztah. One good point is, that would be cool if this limitation appears on the docs… Adding `ostype` annotation there (in addition with that change) *could* allow that (having a badge `linux only` or something), so I'm fine adding the annotation too :angel:

**Comment by thaJeztah** [comment]
Yes. I forgot indeed that `ostype` is checking the daemon OS. Although that still makes sense for this feature (i.e. the CLI and daemon must be on the same host, so it's still "valid"); let's do that in a follow up. Perhaps add a `client_os_type` / `ClientOSType` annotation?

**Pull request merged**
