### PR TITLE
[23.0 backport] improve and load plugin command stubs when required

### LINKED ISSUE #3621: Performance regression on every command invocation
```
cbec75e2f3f5afd3334db693829a6b150612076c is the first bad commit
commit cbec75e2f3f5afd3334db693829a6b150612076c
Author: Nicolas De Loof <nicolas.deloof@gmail.com>
Date:   Wed Mar 30 15:27:25 2022 +0200

    Adopt Cobra completion v2 to support completion by CLI plugins

    Signed-off-by: Nicolas De Loof <nicolas.deloof@gmail.com>

 cli-plugins/manager/cobra.go        | 48 +++++++++++++++---
 cli-plugins/plugin/plugin.go        |  5 ++
...
```

After https://github.com/docker/cli/pull/3429 every command invocation takes ~200ms longer. Even when command just redirects to another process. 

Before:

```
 # time /tmp/docker buildx version
github.com/docker/buildx v0.8.0-92-g908ce2d2.m 908ce2d20618a069ddd06fc4f044505899932fe2.m
/tmp/docker buildx version  0.06s user 0.04s system 98% cpu 0.098 total
 # time /tmp/docker buildx version
github.com/docker/buildx v0.8.0-92-g908ce2d2.m 908ce2d20618a069ddd06fc4f044505899932fe2.m
/tmp/docker buildx version  0.06s user 0.03s system 99% cpu 0.095 total
 # time /tmp/docker buildx version
github.com/docker/buildx v0.8.0-92-g908ce2d2.m 908ce2d20618a069ddd06fc4f044505899932fe2.m
/tmp/docker buildx version  0.06s user 0.03s system 94% cpu 0.096 total
 # time /tmp/docker --version
Docker version unknown-version, build unknown-commit
/tmp/docker --version  0.02s user 0.01s system 71% cpu 0.038 total
 # time /tmp/docker --version
Docker version unknown-version, build unknown-commit
/tmp/docker --version  0.02s user 0.01s system 70% cpu 0.036 total
```

After:
```
github.com/docker/buildx v0.8.0-92-g908ce2d2.m 908ce2d20618a069ddd06fc4f044505899932fe2.m
/tmp/docker buildx version  0.19s user 0.10s system 89% cpu 0.322 total
 # time /tmp/docker buildx version
github.com/docker/buildx v0.8.0-92-g908ce2d2.m 908ce2d20618a069ddd06fc4f044505899932fe2.m
/tmp/docker buildx version  0.19s user 0.10s system 90% cpu 0.325 total
 # time /tmp/docker buildx version
github.com/docker/buildx v0.8.0-92-g908ce2d2.m 908ce2d20618a069ddd06fc4f044505899932fe2.m
/tmp/docker buildx version  0.18s user 0.10s system 90% cpu 0.312 total
 # time /tmp/docker --version
Docker version unknown-version, build unknown-commit
/tmp/docker --version  0.16s user 0.09s system 89% cpu 0.280 total
 # time /tmp/docker --version
Docker version unknown-version, build unknown-commit
/tmp/docker --version  0.16s user 0.09s system 89% cpu 0.272 total
```

@ndeloof

### PR DESCRIPTION
**Pull request by crazy-max**
* backport of
  * https://github.com/docker/cli/pull/4129 (commit c39c711a18cbd9970ac2e040262b830fd6b4e3f9)
  * https://github.com/docker/cli/pull/4151
* fixes #3621 
* related to https://github.com/docker/cli/pull/3429

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Temporarily moved back to draft, as we need to investigate a possible regression; see https://github.com/docker/cli/pull/4142#issuecomment-1491089789

**Comment by crazy-max** [comment]
Removed https://github.com/docker/cli/commit/62f2358b99f8addb4ee1409ac8782610b7cf7030 from backport. PR description updated.

**Comment by crazy-max** [comment]
Moved out of draft if you still wish this work net 23.0

**Review by laurazard — APPROVED** [review]

**Comment by crazy-max** [comment]
@thaJeztah Cherry picked https://github.com/docker/cli/pull/4151 here.

**Review by thaJeztah — APPROVED** [review]
LGTM

I'll wait with merging for now (need to double-check if we want this in the first coming patch release)

**Pull request merged**
