### PR TITLE
docs: remove docs for —-from=index

### PR DESCRIPTION
**Pull request by tonistiigi**
Naming stages is the preferred method for using
multi-stage builds.

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
Is the plan to deprecate the index variant?

**Comment by thaJeztah** [comment]
Also should we clarify that it also accepts images?

**Comment by tonistiigi** [comment]
I'm not sure if we actually need to deprecate. No need to remove and break somebody, but this is generating confusion for new users and should be avoided.

**Comment by tonistiigi** [comment]
> Also should we clarify that it also accepts images?

**Comment by tonistiigi** [comment]
> Also should we clarify that it also accepts images?

There's already a comment for it.

**Comment by thaJeztah** [comment]
@silvin-lubecki PTAL

**Pull request merged**
