### PR TITLE
Added support for setting OS version in docker manifest annotate.

### PR DESCRIPTION
**Pull request by cpuguy83**
Carry of #1461, just rebased.

### CODE REVIEW

**Comment by tonistiigi** [comment]
@cpuguy83 fyi, this use-case is also covered with `buildx imagetools create`

**Comment by sozercan** [comment]
@tonistiigi Is there an example of setting os.version using `buildx imagetools create`? I couldn't find it in https://github.com/docker/buildx#buildx-imagetools-create-options-source-source

**Comment by tonistiigi** [comment]
@sozercan `-f` can point to a file containing the JSON descriptor with all the platform fields and annotations you would want that item to have in the final manifest list. But yes, I agree it could use more docs (and I'm not sure how well tested it is).

Not against this PR as well as clearly seems something that was forgotten, but generally recommend `buildx` instead of manifest command.

**Comment by thaJeztah** [comment]
@tonistiigi ok to go?

**Comment by sjackman** [comment]
> -f can point to a file containing the JSON descriptor with all the platform fields and annotations you would want that item to have in the final manifest list. But yes, I agree it could use more docs (and I'm not sure how well tested it is).

@tonistiigi Could you please give an example of this JSON file?

**Comment by sjackman** [comment]
@tonistiigi wrote…

> fyi, this use-case is also covered with buildx imagetools create

How can `docker buildx imagetools create` set `os.version`?

**Comment by sjackman** [comment]
I successfully uploaded an image index that includes `os.version` using Skopeo! https://github.com/containers/skopeo

**Pull request merged**
