### PR TITLE
Don't prune volumes on `docker system prune`

### PR DESCRIPTION
**Pull request by cpuguy83**
Volumes tend to carry important data and pruning them on `docker system
prune` can easily cause unwanted data loss.

Let's play it safe and not prune volumes on `system prune`.

Throwing this out there.

### CODE REVIEW

**Comment by mlaventure** [comment]
Maybe make it an option? I mean system prune or any other destructive operation are not to be used if you don't know what you're doing :angel:

**Comment by dnephin** [comment]
Making it an option sounds good. `docker-compose down` has a `-v` option for removing volumes. The default is to only remove containers and networks.

**Comment by albers** [comment]
+1 for an option.

**Comment by thaJeztah** [comment]
Yes, I think having an option could make sense, on the other hand, calling `docker volume prune` to cleanup volumes is extra explicit, so may work as well.

Open to both options :blush:

**Comment by cpuguy83** [comment]
We can add an option. THe reason I didn't is it's kind of weird with the existing "--all" option (which is just weird anyway).

**Comment by cpuguy83** [comment]
Added the option.

**Comment by thaJeztah** [comment]
This didn't make it into 17.06, so updated the milestone

**Pull request merged**
