### PR TITLE
[20.10 backport] dockerfile based binary building

### PR DESCRIPTION
**Pull request by tiborvass**
Cherry-picks of #2996 and #2993 with added commit that reverses some changes in the main Makefile to limit the script changes within the same 20.10 release. The main purpose is to have darwin arm64 builds working in 20.10.

### CODE REVIEW

**Comment by kadirselcuk** [comment]
Dep to individual organization teams

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by tonistiigi** [comment]
I guess we technically don't need to backport #2996 unless we really want to make a windows/arm64 release.

**Comment by tonistiigi** [comment]
@cpuguy83 https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/Dockerfile#L14https://github.com/docker/cli/blob/a32cd16160f1b41c1c4ae7bee4dac929d1484e59/Dockerfile#L14 does

But I guess plugins are built somewhere differently that would also need exception so no need to rush with it yet.

**Comment by cpuguy83** [comment]
I really don't like the way this was done. I would also really prefer to not backport this to 20.10 because it breaks downstream builds.

**Comment by tiborvass** [comment]
@tonistiigi Sorry I thought I pushed the changes to remove windows/arm64 and that sys vendor commit. Updated now.

@cpuguy83 I know it's not great to do this in 20.10 which is why I kept the Makefile as backwards compatible as possible while still building the new way. Which part specifically breaks down downstream for you?

**Review by tonistiigi — APPROVED** [review]

**Pull request merged**
