### PR TITLE
Fix missing missing backtick in documentation for node ls

### PR DESCRIPTION
**Pull request by beenanner**

### CODE REVIEW

**Comment by vdemeester** [comment]
@beenanner could you sign your commit ? 👼 🙏

**Comment by beenanner** [comment]
Yes let me do that tonight!  I did this from my work laptop and forgot. ;-p

**Comment by thaJeztah** [comment]
Thanks! Sorry for the extra work for a one-character change, but otherwise CI will keep failing 😅

**Comment by beenanner** [comment]
Sorry for the delay signed and updated. @vdemeester @thaJeztah @mstanleyjones

**Comment by vdemeester** [comment]
@beenanner yay thanks 🎉

**Pull request merged**
