### PR TITLE
Add network and target to build in v3.4

### LINKED ISSUE #305: Add `build.network` field to Compose file v3.x
See https://github.com/docker/compose/pull/4997

### PR DESCRIPTION
**Pull request by dnephin**
Fixes #305
Related https://github.com/docker/compose/pull/5011

This is basically a no-op, but it's good to keep them synced, and it will work when Compose uses the v3.4 schema.

### CODE REVIEW

**Comment by sirlatrom** [comment]
Seeing as multi-stage builds with targets were introduced as part of docker-ce stable 17.06, is there any chance this change will be part of any 17.06.x stable patch release?

**Comment by thaJeztah** [comment]
@sirlatrom `docker stack deploy` doesn't support _build_, so for the docker 17.06 release there's nothing to do; an update to docker compose could support it, but that's a separate repository

**Comment by dnephin** [comment]
cc @shin- just an FYI that we've added these to v3.4

**Comment by sirlatrom** [comment]
@thaJeztah `docker stack deploy` doesn't _support_ the `services.service.build` key, but it _does_ validate its contents, giving errors like shown below. While that is the case, the same docker-compose.yml cannot be used for both building the images and deploying the stack.

`app.go`:
```golang
package main
func main() {
}
```

`Dockerfile`:
```Dockerfile
FROM golang:1.7.3 as builder
WORKDIR /go/src/github.com/alexellis/href-counter/
RUN go get -d -v golang.org/x/net/html
COPY app.go    .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:latest
RUN apk --no-cache add ca-certificates
WORKDIR /root/
COPY --from=builder /go/src/github.com/alexellis/href-counter/app .
CMD ["./app"]
```

`docker-compose.yml`:
```yaml
version: '3.3'
services:
    builder:
        build:
            context: .
            target: builder
    app:
        build:
            context: .
```

Error message:
```bash
$ docker stack deploy --compose-file docker-compose.yml mystack
services.builder.build Additional property target is not allowed

$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:23:31 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:19:04 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

**Pull request merged**
