### PR TITLE
Bump buildkit to 06d81be140e1cb5fdcc77cae927be3be5d40ddca

### PR DESCRIPTION
**Pull request by nogoegst**
It is required for #932.

### CODE REVIEW

**Comment by nogoegst** [comment]
oh no. it turned out to be not that easy.

**Comment by silvin-lubecki** [comment]
Renaming to [WIP] as it seems the PRs needs further work to build.

**Comment by nogoegst** [comment]
It seems that this passes all the tests. Removed WIP from the title.

**Comment by vdemeester** [comment]
@nogoegst thanks for the PR, sorry it took a while, but https://github.com/docker/cli/pull/1116/files bumped `buildkit` to a more recent version, so I'm gonna close this one :angel: sorry :pray:

**Pull request closed without merging**
