### PR TITLE
Azure Container Registry: Docker CLI configuration to allow alternative ways to obtain username/passwords such as AAD device login

### PR DESCRIPTION
**Pull request by shhsu**
- What I did
The motivation of this feature is to allow user of Azure Container Registry to perform a device login with Azure Active Directory (AAD). The user would optionally not need to provide username and password and the login would be done with a token obtained from AAD.
```
>docker login peterhsuaadacr-microsoft.azurecr.io
To sign in, use a web browser to open the page https://aka.ms/devicelogin and enter the code B2BQTS7A2 to authenticate.
Login Succeeded
```
- How I did it
Example config changes
```
{
	"registry-auth-config": [
		{
			"login-module": "acr",
			"condition-server": "*.azurecr.io",
			"condition-type": "Bearer",
			"condition-realm": "https://*.azurecr.io/oauth2/token",
		}
	]
}
```
In the case where user did not provide username or password on login, docker would still hit the url https://{registry}/v2 and receives a challenge with status 401. docker would then read the Www-authenticate header and determine the challenge type and parameters. docker would then try to dispatch the login request to the specified docker-login-{login-module} executable file based on the criteria that the config file specifies. The criteria can be based on the challenge type (Bearer. Basic), challenge Realm, or login server url.

With the above example, if a request is made to any registry with address *.azurecr.io, and the challenge type is Bearer and the challenge realm is https://*.azurecr.io/oauth2/token, docker would call docker-login-acr.exe to perform the login. It would pass the entire content of Www-authenticate header and the login server address to the submodule as parameter. The callee is responsible to reply with an object populated with Username, Password and ServerAddress for docker to perform the final login.

Optionally, the login module can also bail out by passing back empty username and password to ask docker to do a prompt for username and password. This is for backward compatibility.

- How to verify it
I manually verified by running docker login on my AAD enabled registry.
I also checked and the username/password scenario didn't break for

    github itself
    an AAD enabled registry
    an azure docker registry that does not have AAD enabled

### CODE REVIEW

**Comment by shhsu** [comment]
This is the revival of https://github.com/moby/moby/pull/32903
@SajayAntony @sivagms
/cc @jhowardmsft @dmcgowan @aaronlehmann @thaJeztah

**Comment by thaJeztah** [comment]
There's a gofmt error;

```
cli/config/registry/auth_config.go:1::warning: file is not gofmted with -s (gofmt)
cli/config/registry/auth_config.go:1::warning: file is not goimported (goimports)
```

**Comment by shhsu** [comment]
One test failed due to timeout. The other 3 passed. Does this mean gofmt error fixed?

**Comment by friism** [comment]
@shhsu have you looked at doing this with a credentialhelper instead? The credentialhelper could just read from whereever the azure cli stores creds. Different helpers can be configured for different registries.

It looks like wildcard matching is not currently done, but that seems like a reasonable change (although I'm not an expert on the topic): https://github.com/docker/cli/blob/dee8e6ab2da3fe1f57f57de6c009a9256040d1d0/cli/command/cli.go#L148

**Comment by shhsu** [comment]
@friism Not sure if I understand you completely but I am not seeing how credentialhelper could help here. This feature allows interactive login to interactively get the credentials. After the credential is retrieved, the credentials would still be stored with whatever credentialhelper is configured. We are not assuming any credential stored.

**Comment by friism** [comment]
@shhsu it would make usage even simpler: Users would configure your credential-helper for a wildcard domain that matches all Azure registries, and then they can start doing `docker push/pull` without further ado. They just have to be logged in to Azure with `azure login` (or the PowerShell equivalent).

The approach I outlined seems simpler to me since Docker won't have to carry code specific to how login works on Azure (not that there's anything wrong with Azure login).

Imagine, for example, that a security flaw was found in the Azure login flow. With the change you propose in Docker, you'd have to scramble to fix that in Azure tools and CLIs, _and_ you'd have to get a fix into Docker and goad us into action to urgently ship the fix.

If we accepted similar contributions from other registry vendors then that would be hard to scale for us, and if you got similar changes into more software like Docker, it would be equally hard for you to scale fixing problems all the places that implemented Azure login.

With the approach I suggested, you wouldn't have to implement another piece of software that implements `azure login`.

**Comment by friism** [comment]
@shhsu what do you think? Did my comment make sense?

**Comment by shhsu** [comment]
@friism 
Yes, I will be redesigning the feature accordingly.

**Pull request closed without merging**
