### PR TITLE
Adding example of != in command list

### PR DESCRIPTION
**Pull request by david-yu**
Adding != filter example to command list

**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by david-yu** [comment]
@tiborvass This is the PR that implemented this change: https://github.com/moby/moby/pull/30740/

**Comment by david-yu** [comment]
@thaJeztah Just changed the examples

**Comment by thaJeztah** [comment]
Looks like this needs a sign-off and squash, but also needs to have the same changes in the actual code (which is what's used to generate the online documentation).

I'm a bit in doubt if we should add too many examples here

**Comment by thaJeztah** [comment]
closing for now

**Pull request closed without merging**
