### PR TITLE
Fix grammar

### PR DESCRIPTION
**Pull request by mvasin**
Grammar nazi in the house.

### CODE REVIEW

**Comment by mvasin** [comment]
@thaJeztah Sure, please have a look.

**Comment by thaJeztah** [comment]
oops, looks you accidentally removed the `signed-off by:` in the process; one more update?

**Comment by mvasin** [comment]
@thaJeztah Done!

**Comment by thaJeztah** [comment]
Congrats on your first PR merged in this repository 🎉

**Pull request merged**
