### PR TITLE
Add composefile schema 3.7 with platform

### PR DESCRIPTION
**Pull request by vdemeester**
It's ignored for now (docker stack deploy) and will print a warning if present.

Fixes https://github.com/docker/cli/issues/1050

> That being said, I think one *easy fix* to that issue would be to add `platform` to v3 schema(s) — but it would start at schema `3.7` — **and** printing a warning when issuing a `docker stack deploy` that this field is not supported (same way we do it for `build`). It would allow to more easily updated from v2 to v3 for users and help us not make v2 and v3 schema diverge that much — at least not having elements in v2 that are not in v3…

Also linked to https://github.com/docker/compose/pull/5985

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

**Comment by shin-** [comment]
Are we really okay with adding non-Swarm compatible options to v3? I'm asking because it's a significant depart from our strategy so far (with the exception of build sub-options) and I'm curious how it'll affect user experience.

I'm guessing the rationale is that Swarm (/kube?) will support the option eventually?

**Comment by vdemeester** [comment]
> I'm guessing the rationale is that Swarm (/kube?) will support the option eventually?

Yes, that's part of the rationale — other part is I really wish we have as divergence between v2 and v3 composefile evolution 👼

**Comment by casz** [comment]
How rigid do you want to be? Docker compose should perhaps support an experimental flag just like the docker for windows? So that we can get to try out the new stuff. Maybe I am asking for too much, I don't know. 🤔

**Comment by thaJeztah** [comment]
> How rigid do you want to be?

Well, a spec, once published, cannot be changed, so that's why I want to be sure it's finalised and agreed on.

> Docker compose should perhaps support an experimental flag

Having this as an [extension field](https://docs.docker.com/compose/compose-file/#extension-fields) (`x-platform: foo`) would be an option for that

**Comment by vdemeester** [comment]
Closing this as it staled :sweat:

**Comment by casz** [comment]
no worries @vdemeester fixed by the auto-detection, so it's fine :)

**Pull request closed without merging**
