### PR TITLE
update go to 1.17

### PR DESCRIPTION
**Pull request by tonistiigi**
Removes the platform-based switch between different versions.

Signed-off-by: Tonis Tiigi <tonistiigi@gmail.com>

### CODE REVIEW

**Comment by thaJeztah** [comment]
We should check if `moby/moby` also builds with go 1.17. The release pipeline currently assumes the same version is used for both

**Review by AkihiroSuda — CHANGES_REQUESTED** [review]
Go 1.17 on macOS requires https://github.com/golang/sys/commit/a76c4d0a0096537dc565908b53073460d96c8539 (May 8) or later.

The current version in vendor.conf is https://github.com/golang/sys/commit/d19ff857e887eacb631721f188c7d365c2331456 (Apr 27)

**Comment by thaJeztah** [comment]
opened https://github.com/moby/moby/pull/42777 to test moby on go 1.17

**Comment by thaJeztah** [comment]
opened https://github.com/docker/cli/pull/3269 to update golang.org/x/sys in this repository

**Pull request closed without merging**
