### PR TITLE
Remove duplicate word in push.md

### PR DESCRIPTION
**Pull request by rochfeu**
**- What I did**

**- How I did it**

**- How to verify it**

**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Thanks for contributing! Change itself looks good, but looks like the commit message is [missing a DCO sign-off](https://github.com/docker/cli/blob/master/CONTRIBUTING.md#sign-your-work), which causes CI to fail; you can find instructions on how to fix this from the command-line (unfortunately, it's not possible to fix commit messages from the GitHub webUI 😞); https://github.com/docker/cli/pull/2915/checks?check_run_id=1655200518

When fixing, make sure to use your real name, not your GitHub handle/name; let me know if you need help making those changes, thanks!

**Comment by rochfeu** [comment]
> When fixing, make sure to use your real name, not your GitHub handle/name; let me know if you need help making those changes, thanks!

I just did it but DCO CI fails and asks for my GitHub pseudo:
> Commit sha: 69b5487, Author: rochfeu, Committer: Roch; Expected "rochfeu 46478807+rochfeu@users.noreply.github.com", but got "Roch Feuillade roch.feuillade@pandobac.com".

**Comment by thaJeztah** [comment]
> I just did it but DCO CI fails and asks for my GitHub pseudo:

Ah, yes, I think it may be checking against the name you have configure in your `git` config;

```
config user.name
Sebastiaan van Stijn
```

You can update your git config to match, which should fix that; https://github.com/moby/moby/blob/v20.10.0/docs/contributing/set-up-git.md#task-2-set-your-signature-and-an-upstream-remote

No no worries,  I can manually mark it as "passed" for this case 👍

**Review by thaJeztah — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
