### PR TITLE
add cross compile for linux/ppc64le

### PR DESCRIPTION
**Pull request by andrewhsu**
To support other arch as mentioned in #31 

Signed-off-by: Andrew Hsu <andrewhsu@docker.com>

### CODE REVIEW

**Comment by dnephin** [comment]
needs a rebase to pickup circleci fixes

otherwise LGTM

**Comment by dnephin** [comment]
I'm trying this out and I'm getting this error:
```
1 errors occurred:
--> linux/ppc64le error: exit status 2
Stderr: # github.com/docker/cli/vendor/github.com/docker/docker/pkg/term
vendor/github.com/docker/docker/pkg/term/term.go:53: undefined: tcget
vendor/github.com/docker/docker/pkg/term/term.go:62: undefined: tcset
vendor/github.com/docker/docker/pkg/term/term.go:71: undefined: tcget
vendor/github.com/docker/docker/pkg/term/term.go:84: undefined: tcset

```

I think we merged something in pkg/term recently

**Comment by tophj-ibm** [comment]
hmm... I can't recreate this on x86 or ppc64le, but this looks like the case where pkg/term/tc_linux_cgo.go (which re-definies tcget/tcset) isn't being built for ppc64le because CGO isn't enabled.

@tiborvass and I did fix an issue with this last week, maybe this just needs a rebase.

**Comment by dnephin** [comment]
To clarify, I saw the problem when I did a rebase. You can also see it on my branch in #78 if you enable it in linux-cross

**Comment by tophj-ibm** [comment]
Gotcha. I opened up https://github.com/moby/moby/pull/33180 which should fix the underlying issue. (syscall is way outdated)

**Comment by dnephin** [comment]
replaced by #104

**Pull request closed without merging**
