### PR TITLE
Use scope=swarm for service related network inspect and revendor docker/docker

### PR DESCRIPTION
**Pull request by yongtang**
This fix updates docker/docker to 4310f7da7e6bcd8185bf05e032f9b7321cfa6ea2 and use `scope=swarm` for service related network inspect.

This fix use `scope=swarm` for service related network inspect. The purpose is that, in case multiple networks with the same name exist in different scopes, it is still possible to obtain the network for services.

This fix is related to  docker/cli#167, moby/moby#30897, moby/moby#33561, moby/moby#30242

### CODE REVIEW

**Comment by aaronlehmann** [comment]
Sorry for my ignorance about network scoping, but I see that the node-local networks PR (https://github.com/moby/moby/pull/32981) says it added the `scope=swarm` option to `network create`. Will the change here work correctly with networks that were created before that PR, and networks that are not node-local?

The only comment I have on the code itself is that there are many places that specify `Verbose: false`, but these are not needed because `Verbose` will default to `false`.

**Comment by dnephin** [comment]
I believe network scopes have existed since swarm was integrated, we just started exposing them to new endpoints more recently. So every swarm network should alredy have `scope=swarm` even if it was created before that PR.

**Comment by yongtang** [comment]
Thanks all for the review. The PR has been updated and now the unnecessary `Verbose: false` has been removed.

For moby/moby#32981, it adds allows a node-local network to be promoted to the `swarm` scope. Once a previous node-local network is promoted to `swarm` scope, it will be possible to be used by service created. For that the `scope=swarm` option passed in this PR is consistent with moby/moby#32981

**Comment by aaronlehmann** [comment]
LGTM

**Pull request merged**
