### PR TITLE
Update compose-on-kubernetes v0.4.20

### PR DESCRIPTION
**Pull request by thaJeztah**
ping @simonferquel @silvin-lubecki PTAL

### CODE REVIEW

**Comment by simonferquel** [comment]
lgtm (but I will soon open a PR to expose Load-Balanced intra-stack networking feature, and will have to revert to master)

**Comment by thaJeztah** [comment]
ping @silvin-lubecki @vdemeester PTAL

**Comment by thaJeztah** [comment]
oh damn; conflicts - perhaps someone could rebase this?

**Comment by thaJeztah** [comment]
nvm: it was an easy one; fixed

**Comment by simonferquel** [comment]
Actually we'll soon create a tag with updated vendoring of kubernetes to 1.13x (instead of 1.11x) for compatibility with 1.11-1.15 kubernetes clusters.
(we detected issues with the cli and clusters running Kubernetes 1.14 last friday)

Can we defer this (and bump to 0.4.21 when it lands)?

**Comment by thaJeztah** [comment]
I see 0.4.21 was tagged, but it's still using an RC for Kubernetes, correct? https://github.com/docker/compose-on-kubernetes/releases/tag/v0.4.21-kube-v1.14.0-rc.1

**Comment by simonferquel** [comment]
@thaJeztah Correct, I am currently doing the GA vendoring. v0.4.21 should be out later today, or tomorrow. (I guess we should use #1774 as the starting base to merge it though).

**Comment by thaJeztah** [comment]
But https://github.com/docker/cli/pull/1774 would bump it to kube 1.13.x, guess we should skip that if we need Kubernetes 1.14?

**Comment by simonferquel** [comment]
We will update it to vendor 1.14 ga

**Comment by thaJeztah** [comment]
closing in favour of https://github.com/docker/cli/pull/1774

**Pull request closed without merging**
