### PR TITLE
Dockerfile: update tonistiigi/xx to 1.0.0-rc.2, add XX_VERSION arg

### PR DESCRIPTION
**Pull request by thaJeztah**
**- Description for the changelog**

**- A picture of a cute animal (not mandatory but encouraged)**

### CODE REVIEW

**Comment by thaJeztah** [comment]
@crazy-max @silvin-lubecki PTAL

**Review by crazy-max — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
wait with merge; I'll do a Go version bump first (and will rebase this after)

**Review by silvin-lubecki — APPROVED** [review]
LGTM

**Comment by thaJeztah** [comment]
Let me do a rebase to get rid of the merge commit

**Comment by thaJeztah** [comment]
all green again (after rebase) bringing this one in

**Pull request merged**
