### PR TITLE
e2e: use stable-dind image for testing

### PR DESCRIPTION
**Pull request by thaJeztah**
The edge channel is deprecated and no longer updated

### CODE REVIEW

**Comment by thaJeztah** [comment]
@silvin-lubecki @vdemeester PTAL; wasn't sure what we preferred here;

- use `test-dind` (latest "RC"); gives the advantage of testing against latest/greatest, but this image may change at points so possibly cause inconsistent results
- use `stable-dind` same "problem" as above
- pin to a specific version (this PR); downside is that we don't catch regressions, but positive side is that we know what we're testing against

**Comment by vdemeester** [comment]
> @silvin-lubecki @vdemeester PTAL; wasn't sure what we preferred here;
> 
>     * use `test-dind` (latest "RC"); gives the advantage of testing against latest/greatest, but this image may change at points so possibly cause inconsistent results
> 
>     * use `stable-dind` same "problem" as above
> 
>     * pin to a specific version (this PR); downside is that we don't catch regressions, but positive side is that we know what we're testing against

I think safest bet is `stable-dind`. We could have another job `test-dind` that is not a blocker (aka we would see it needs fixing but it wouldn't be required to be green to be able to merge). @thaJeztah wdyt ?

**Comment by thaJeztah** [comment]
I'm good with `stable-dind` (less maintenance) let me update

**Comment by thaJeztah** [comment]
updated 👍

**Pull request merged**
