### PR TITLE
remove service runtime filter from client

### PR DESCRIPTION
**Pull request by gdevillele**
it’s moving to the server.

Based on @ehazlett 's PR:
https://github.com/moby/moby/pull/32813/commits/e2d53387614f27782e905389f6f7a727dd21af05

Signed-off-by: Gaetan de Villele <gdevillele@gmail.com>

### CODE REVIEW

**Comment by dnephin** [comment]
Let's wait until the PR merges on moby/moby to merge this.

We also need CI I think

**Comment by gdevillele** [comment]
I agree on both points.
I have been thinking about the CI, and that's why I want to have the code to compile on all supported platforms.

**Comment by gdevillele** [comment]
PR has been merged on moby/moby.

**Comment by ehazlett** [comment]
LGTM

**Pull request merged**
